#ifndef _SLOTMAP_DEBUGCOMMAND_H_
#define _SLOTMAP_DEBUGCOMMAND_H_

#define SLOT_CMD 8
#define SLOT_CMD_1 9
#define SLOT_CMD_AZ 11
#define SLOT_CMD_AZAZAZAZ 13
#define SLOT_CMD_CONTC 2
#define SLOT_CMD_HELPH 4
#define SLOT_CMD_INPUTSOFFSETSTEXTS 7
#define SLOT_CMD_INSTRSAZ 10
#define SLOT_CMD_LABELSAZAZAZAZ 12
#define SLOT_CMD_NEXTN 0
#define SLOT_CMD_OVERO 3
#define SLOT_CMD_QUITQ 1
#define SLOT_CMD_STATE 6
#define SLOT_CMD_VERBOSEV 5

#endif
