/**
* \file
* \brief This file is an autogenerated function prototypes header file.
*
* Copyright 2018 K.J. Hermans
* WARNING: This file is automatically generated. Any changes will be lost.
*/

#ifndef ___LIB_DISASSEMBLER_FUNCTIONS_H_
#define ___LIB_DISASSEMBLER_FUNCTIONS_H_

/* declared in ./lib/disassembler/naid_disassemble.c */
extern
NAIG_ERR_T naid_disassemble
  (
    unsigned char* bytecode,
    unsigned bytecode_length,
    NAIG_ERR_T (*write)(void* ptr, char* fmt, ...),
    void* arg
  )
  __attribute__ ((warn_unused_result));

/* declared in ./lib/disassembler/naid_do_disassemble.c */
extern
NAIG_ERR_T naid_do_disassemble
  (naid_t* naid)
  __attribute__ ((warn_unused_result));



#endif