/**
* \file
* \brief This file is an autogenerated function prototypes header file.
*
* Copyright 2018 K.J. Hermans
* WARNING: This file is automatically generated. Any changes will be lost.
*/

#ifndef _NAIGAMA_SERVICE_FUNCTIONS_H_
#define _NAIGAMA_SERVICE_FUNCTIONS_H_

/* declared in ./lib/service/nais_configure.c */
extern
NAIG_ERR_T nais_configure
  (nais_t* nais)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/service/nais_configure_side.c */
extern
NAIG_ERR_T nais_configure_side
  (nais_t* nais, naio_resobj_t* o, unsigned side)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/service/nais_json_path.c */
extern
NAIG_ERR_T nais_json_path
  (naio_resobj_t* o, unsigned nelts, char* elts[], naio_resobj_t** result)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/service/nais_json_path_string.c */
extern
char* nais_json_path_string
  (naio_resobj_t* top, unsigned nelts, char* elts[])
  __attribute__ ((warn_unused_result));

/* declared in ./lib/service/nais_loop.c */
extern
NAIG_ERR_T nais_loop
  (nais_t* nais)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/service/nais_process_data.c */
extern
NAIG_ERR_T nais_process_data
  (nais_t* nais, nais_ctx_t* context)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/service/nais_process_mgmt.c */
extern
NAIG_ERR_T nais_process_mgmt
  (nais_t* nais)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/service/nais_scheduler.c */
extern
NAIG_ERR_T nais_scheduler
  (nais_t* nais, time_t t)
  __attribute__ ((warn_unused_result));



#endif