OBJECTS = \
  thrd_driver.o \
  thrd_life.o \
  thrd_stop.o \
  thrdpl_add_job.o \
  thrdpl_do_job.o \
  thrdpl_get_thread.o \
  thrdpl_life.o \
  thrdpl_stop.o \
  thrdpl_relnq_thread.o \
  thrdpl_set_logfile.o \
  thrdpl_set_logpath.o \
  thrdpl_set_maxbusy.o \


CFLAGS = $(PROTOCFLAGS)

TARGET = libthrdpl.a

all: $(OBJECTS) target

target: $(TARGET)

$(TARGET): $(OBJECTS)
	@/bin/echo "  Building archive"; ar -rcs $(TARGET) $(OBJECTS)

clean:
	rm -f $(OBJECTS) $(TARGET)

%.o: %.c
	@/bin/echo -n "  Compiling $< .. "; \
	if $(CC) $(CFLAGS) -c -o $@ $<; then \
	  /bin/echo "Ok"; \
	else \
	  /bin/echo "Failed: $(CC) $(CFLAGS) -c -o $@ $<"; \
	  exit -1; \
	fi
