#define ASMSLOTMAP_SWITCH \
  case 0: return "INSTRUCTION_ANYINSTRBACKCOMMITIN"; break; \
  case 1: return "ANYINSTR_ANY"; break; \
  case 2: return "BACKCOMMITINSTR_BACKCOMMIT"; break; \
  case 3: return "CALLINSTR_CALL"; break; \
  case 4: return "CATCHINSTR_CATCH"; break; \
  case 5: return "CHARINSTR_CHAR"; break; \
  case 6: return "MASKEDCHARINSTR_MASKEDCHAR"; break; \
  case 7: return "CLOSECAPTUREINSTR_CLOSECAPTURE"; break; \
  case 8: return "COMMITINSTR_COMMIT"; break; \
  case 9: return "ENDINSTR_END"; break; \
  case 10: return "FAILINSTR_FAIL"; break; \
  case 11: return "FAILTWICEINSTR_FAILTWICE"; break; \
  case 12: return "JUMPINSTR_JUMP"; break; \
  case 13: return "NOOPINSTR_NOOP"; break; \
  case 14: return "TRAPINSTR_TRAP"; break; \
  case 15: return "OPENCAPTUREINSTR_OPENCAPTURE"; break; \
  case 16: return "PARTIALCOMMITINSTR_PARTIALCOMMIT"; break; \
  case 17: return "QUADINSTR_QUAD"; break; \
  case 18: return "REPLACEINSTR_REPLACE"; break; \
  case 19: return "ENDREPLACEINSTR_ENDREPLACE"; break; \
  case 20: return "RETINSTR_RET"; break; \
  case 21: return "SETINSTR_SET"; break; \
  case 22: return "RANGEINSTR_RANGE"; break; \
  case 23: return "SKIPINSTR_SKIP"; break; \
  case 24: return "SPANINSTR_SPAN"; break; \
  case 25: return "TESTANYINSTR_TESTANY"; break; \
  case 26: return "TESTCHARINSTR_TESTCHAR"; break; \
  case 27: return "TESTQUADINSTR_TESTQUAD"; break; \
  case 28: return "TESTSETINSTR_TESTSET"; break; \
  case 29: return "VARINSTR_VAR"; break; \
  case 30: return "COUNTERINSTR_COUNTER"; break; \
  case 31: return "CONDJUMPINSTR_CONDJUMP"; break; \
  case 32: return "ISOLATEINSTR_ISOLATE"; break; \
  case 33: return "ENDISOLATEINSTR_ENDISOLATE"; break; \
  case 34: return "LABELDEF_LABEL"; break; \
  case 35: return "SCR_ADD_SADD"; break; \
  case 36: return "SCR_CALL_SCALL"; break; \
  case 37: return "SCR_PUSH_SPUSH"; break; \
  case 38: return "SCR_RET_SRET"; break; \
  case 39: return "SCR_BUILTIN_SBUILTIN"; break; \
  case 40: return "SCR_STRING_SSTRING"; break; \
  case 41: return "HEXBYTE_AFAF"; break; \
  case 42: return "LABEL_AZAZ"; break; \
  case 43: return "NUMBER"; break; \
  case 44: return "QUAD_AFAF"; break; \
  case 45: return "SET_AFAF"; break; \
  case 46: return "FUNCTIONBARRIER_FUNCTION"; break; \
  case 47: return "STRINGREF_STRING"; break; \
  case 48: return "STRINGLITERAL_NRTV"; break; \
  case 49: return "REGISTERREF_NUMBER"; break; \
  case 50: return "FLOATLITERAL"; break; \
  case 51: return "INTLITERAL"; break; \
  case 52: return "BOOLEANLITERAL_TRUEFALSE"; break; \
  case 53: return "VOIDLITERAL_VOID"; break; \


#define ASMSLOT_INSTRUCTION_ANYINSTRBACKCOMMITIN 0
#define ASMSLOT_ANYINSTR_ANY 1
#define ASMSLOT_BACKCOMMITINSTR_BACKCOMMIT 2
#define ASMSLOT_CALLINSTR_CALL 3
#define ASMSLOT_CATCHINSTR_CATCH 4
#define ASMSLOT_CHARINSTR_CHAR 5
#define ASMSLOT_MASKEDCHARINSTR_MASKEDCHAR 6
#define ASMSLOT_CLOSECAPTUREINSTR_CLOSECAPTURE 7
#define ASMSLOT_COMMITINSTR_COMMIT 8
#define ASMSLOT_ENDINSTR_END 9
#define ASMSLOT_FAILINSTR_FAIL 10
#define ASMSLOT_FAILTWICEINSTR_FAILTWICE 11
#define ASMSLOT_JUMPINSTR_JUMP 12
#define ASMSLOT_NOOPINSTR_NOOP 13
#define ASMSLOT_TRAPINSTR_TRAP 14
#define ASMSLOT_OPENCAPTUREINSTR_OPENCAPTURE 15
#define ASMSLOT_PARTIALCOMMITINSTR_PARTIALCOMMIT 16
#define ASMSLOT_QUADINSTR_QUAD 17
#define ASMSLOT_REPLACEINSTR_REPLACE 18
#define ASMSLOT_ENDREPLACEINSTR_ENDREPLACE 19
#define ASMSLOT_RETINSTR_RET 20
#define ASMSLOT_SETINSTR_SET 21
#define ASMSLOT_RANGEINSTR_RANGE 22
#define ASMSLOT_SKIPINSTR_SKIP 23
#define ASMSLOT_SPANINSTR_SPAN 24
#define ASMSLOT_TESTANYINSTR_TESTANY 25
#define ASMSLOT_TESTCHARINSTR_TESTCHAR 26
#define ASMSLOT_TESTQUADINSTR_TESTQUAD 27
#define ASMSLOT_TESTSETINSTR_TESTSET 28
#define ASMSLOT_VARINSTR_VAR 29
#define ASMSLOT_COUNTERINSTR_COUNTER 30
#define ASMSLOT_CONDJUMPINSTR_CONDJUMP 31
#define ASMSLOT_ISOLATEINSTR_ISOLATE 32
#define ASMSLOT_ENDISOLATEINSTR_ENDISOLATE 33
#define ASMSLOT_LABELDEF_LABEL 34
#define ASMSLOT_SCR_ADD_SADD 35
#define ASMSLOT_SCR_CALL_SCALL 36
#define ASMSLOT_SCR_PUSH_SPUSH 37
#define ASMSLOT_SCR_RET_SRET 38
#define ASMSLOT_SCR_BUILTIN_SBUILTIN 39
#define ASMSLOT_SCR_STRING_SSTRING 40
#define ASMSLOT_HEXBYTE_AFAF 41
#define ASMSLOT_LABEL_AZAZ 42
#define ASMSLOT_NUMBER 43
#define ASMSLOT_QUAD_AFAF 44
#define ASMSLOT_SET_AFAF 45
#define ASMSLOT_FUNCTIONBARRIER_FUNCTION 46
#define ASMSLOT_STRINGREF_STRING 47
#define ASMSLOT_STRINGLITERAL_NRTV 48
#define ASMSLOT_REGISTERREF_NUMBER 49
#define ASMSLOT_FLOATLITERAL 50
#define ASMSLOT_INTLITERAL 51
#define ASMSLOT_BOOLEANLITERAL_TRUEFALSE 52
#define ASMSLOT_VOIDLITERAL_VOID 53
