/**
* \file
* \brief This file is an autogenerated function prototypes header file.
*
* Copyright 2018 K.J. Hermans
* WARNING: This file is automatically generated. Any changes will be lost.
*/

#ifndef ___LIB_ENGINE_FUNCTIONS_H_
#define ___LIB_ENGINE_FUNCTIONS_H_

/* declared in ./lib/engine/nase_loop.c */
extern
NAIG_ERR_T nase_loop
  (
    nase_t* engine,
    unsigned char* bytecode,
    unsigned bytecode_length,
    nase_result_t* result
  )
  __attribute__ ((warn_unused_result));



#endif