/**
* \file
* \brief This file is an autogenerated function prototypes header file.
*
* Copyright 2018 K.J. Hermans
* WARNING: This file is automatically generated. Any changes will be lost.
*/

#ifndef _NAID_FUNCTIONS_FUNCTIONS_H_
#define _NAID_FUNCTIONS_FUNCTIONS_H_

/* declared in ./naid_disassemble.c */
extern
NAIG_ERR_T naid_disassemble
  (naid_t* naid, char* inputfile)
  __attribute__ ((warn_unused_result));

/* declared in ./naid_parse.c */
extern
NAIG_ERR_T naid_parse
  (naid_t* naid, char* path)
  __attribute__ ((warn_unused_result));



#endif