/**
* \file
* \brief This file is an autogenerated function prototypes header file.
*
* Copyright 2018 K.J. Hermans
* WARNING: This file is automatically generated. Any changes will be lost.
*/

#ifndef _NAIG_FUNCTIONS_FUNCTIONS_H_
#define _NAIG_FUNCTIONS_FUNCTIONS_H_

/* declared in ./naig_result_object.c */
extern
naig_resobj_t* naig_result_object
  (
    const unsigned char* input,
    unsigned inputlength,
    naie_actionlist_t* result
  )
  __attribute__ ((warn_unused_result));

/* declared in ./naig_result_object_clean.c */
extern
void naig_result_object_clean
  (naig_resobj_t* object, unsigned slot);

/* declared in ./naig_result_object_debug.c */
extern
void naig_result_object_debug_
  (naig_resobj_t* object, char*(*fnc)(unsigned), unsigned indent);

/* declared in ./naig_result_object_debug.c */
extern
void naig_result_object_debug
  (naig_resobj_t* object, char*(*fnc)(unsigned));

/* declared in ./naig_result_object_free.c */
extern
void naig_result_object_free
  (naig_resobj_t* object);

/* declared in ./naig_result_object_iterate.c */
extern
NAIG_ERR_T naig_result_object_iterate
  (naig_resobj_t* resobj, unsigned nelts, naig_resobj_itelt_t* elts)
  __attribute__ ((warn_unused_result));

/* declared in ./naig_result_object_path.c */
extern
naig_resobj_t* naig_result_object_path
  (naig_resobj_t* parent, unsigned nargs, ...)
  __attribute__ ((warn_unused_result));

/* declared in ./naig_result_object_query.c */
extern
naig_resobj_t* naig_result_object_query
  (naig_resobj_t* parent, unsigned nargs, ...)
  __attribute__ ((warn_unused_result));

/* declared in ./naip_result_object.c */
extern
naig_resobj_t* naip_result_object
  (
    const unsigned char* input,
    unsigned inputlength,
    naip_actionlist_t* result
  )
  __attribute__ ((warn_unused_result));



#endif