stage_11:
#	@cd processor && make
	@cd engine && make -j 4
	@cd compiler && make -j 4
	@cd assembler && make -j 4
#	@cd util && make -j 4
#	@cd naigama && make -j 4

clean:
	@cd processor && make clean
	@cd engine && make clean
	@cd compiler && make clean
	@cd assembler && make clean
#	@cd util && make clean
#	@cd naigama && make clean

superclean: clean

