#ifndef _SLOTMAP_GRAMMAR_H_
#define _SLOTMAP_GRAMMAR_H_

/* Generated by genslthdr in ./grammar/grammar.slotmap */

#define SLOT_GRAMMAR 0
#define SLOT_S 1
#define SLOT_MULTILINECOMMENT 2
#define SLOT_COMMENT 3
#define SLOT_END 4
#define SLOT_DEFINITION 5
#define SLOT_SINGLE_EXPRESSION 6
#define SLOT_RULE 7
#define SLOT_EXPRESSION 8
#define SLOT_ALTERNATIVES 9
#define SLOT_TERMS 10
#define SLOT_TERM 11
#define SLOT_SCANMATCHER 12
#define SLOT_QUANTIFIEDMATCHER 13
#define SLOT_QUANTIFIER 14
#define SLOT_Q_ZEROORONE 15
#define SLOT_Q_ONEORMORE 16
#define SLOT_Q_ZEROORMORE 17
#define SLOT_Q_FROMTO 18
#define SLOT_Q_FROMTO_1 19
#define SLOT_Q_FROMTO_2 20
#define SLOT_Q_UNTIL 21
#define SLOT_Q_UNTIL_1 22
#define SLOT_Q_FROM 23
#define SLOT_Q_FROM_1 24
#define SLOT_Q_SPECIFIC 25
#define SLOT_Q_SPECIFIC_1 26
#define SLOT_Q_VAR 27
#define SLOT_MATCHER 28
#define SLOT_BITMASK 29
#define SLOT_VARCAPTURE 30
#define SLOT_CAPTURETYPE 31
#define SLOT_TYPE 32
#define SLOT_CAPTURE 33
#define SLOT_GROUP 34
#define SLOT_CAPTUREEND 35
#define SLOT_SET 36
#define SLOT_SET_NRTV 37
#define SLOT_SET_NRTV_1 38
#define SLOT_SET_NRTV_2 39
#define SLOT_VARREFERENCE 40
#define SLOT_MASK 41
#define SLOT_MASK_AFAF 42
#define SLOT_REFERENCE 43
#define SLOT_LIMITEDCALL 44
#define SLOT_LCMODES 45
#define SLOT_LCPARAM 46
#define SLOT_REPLACE 47
#define SLOT_REPLACETERMS 48
#define SLOT_REPLACETERM 49
#define SLOT_RECYCLE 50
#define SLOT_LEFTARROW 51
#define SLOT_RIGHTARROW 52
#define SLOT_FATARROW 53
#define SLOT_NOT 54
#define SLOT_AND 55
#define SLOT_MACRO 56
#define SLOT_ENDFORCE 57
#define SLOT_HEXLITERAL 58
#define SLOT_NUMBER 59
#define SLOT_STRING 60
#define SLOT_OR 61
#define SLOT_ANY 62
#define SLOT_SETNOT 63
#define SLOT_IMPORTDECL 64
#define SLOT_TYPEDECL 65
#define SLOT_FUNCDECL 66
#define SLOT_FUNCPARAMDECL 67
#define SLOT_PARAMDECL 68
#define SLOT_FUNCBODY 69
#define SLOT_GLOBALVARDECL 70
#define SLOT_FUNCSTMT 71
#define SLOT_BLOCKSTMT 72
#define SLOT_ST_IF 73
#define SLOT_CONDITION 74
#define SLOT_BLOCK 75
#define SLOT_IF_ELSIF 76
#define SLOT_IF_ELSE 77
#define SLOT_ST_WHILE 78
#define SLOT_ST_CATCH 79
#define SLOT_ST_RETURN 80
#define SLOT_ST_LOOPCTL 81
#define SLOT_VARDECL 82
#define SLOT_ASSIGNMENT 83
#define SLOT_SCR_TYPE 84
#define SLOT_SCR_EXPRESSION 85
#define SLOT_BINOP_P12 86
#define SLOT_BINOP_P11 87
#define SLOT_BINOP_P10 88
#define SLOT_BINOP_P09 89
#define SLOT_BINOP_P08 90
#define SLOT_BINOP_P07 91
#define SLOT_BINOP_P06 92
#define SLOT_BINOP_P05 93
#define SLOT_BINOP_P04 94
#define SLOT_BINOP_P03 95
#define SLOT_UNOP 96
#define SLOT_SCR_TERM 97
#define SLOT_SCR_UREFERENCE 98
#define SLOT_FUNCTIONCALL 99
#define SLOT_ARGSLIST 100
#define SLOT_SCR_REFERENCE 101
#define SLOT_INDEX 102
#define SLOT_LITERAL 103
#define SLOT_STRINGLITERAL 104
#define SLOT_STRINGLITERAL_NRTV 105
#define SLOT_LISTLITERAL 106
#define SLOT_LISTELT 107
#define SLOT_FLOATLITERAL 108
#define SLOT_INTLITERAL 109
#define SLOT_BOOLEANLITERAL 110
#define SLOT_KW_IMPORT 111
#define SLOT_KW_TYPE 112
#define SLOT_KW_FUNCTION 113
#define SLOT_KW_VAR 114
#define SLOT_KW_WHILE 115
#define SLOT_KW_RETURN 116
#define SLOT_KW_IF 117
#define SLOT_KW_ELSIF 118
#define SLOT_KW_ELSE 119
#define SLOT_KW_BREAK 120
#define SLOT_KW_CONTINUE 121
#define SLOT_KW_CATCH 122
#define SLOT_IDENT 123
#define SLOT_BOPEN 124
#define SLOT_BCLOSE 125
#define SLOT_CBOPEN 126
#define SLOT_CBCLOSE 127
#define SLOT_ABOPEN 128
#define SLOT_ABCLOSE 129
#define SLOT_ASSIGN 130
#define SLOT_EQUALS 131
#define SLOT_NEQUALS 132
#define SLOT_LT 133
#define SLOT_GT 134
#define SLOT_LTEQ 135
#define SLOT_GTEQ 136
#define SLOT_SEMICOLON 137
#define SLOT_COLON 138
#define SLOT_POW 139
#define SLOT_MUL 140
#define SLOT_DIV 141
#define SLOT_ADD 142
#define SLOT_SUB 143
#define SLOT_LOGAND 144
#define SLOT_LOGOR 145
#define SLOT_LOGNOT 146
#define SLOT_BITAND 147
#define SLOT_BITOR 148
#define SLOT_BITXOR 149
#define SLOT_BITNOT 150
#define SLOT_COMMA 151
#define SLOT_DOT 152
#define SLOT_LSHIFT 153
#define SLOT_RSHIFT 154

#define _SLOTMAP_GRAMMAR_SWITCH \
  case 0: return "SLOT_GRAMMAR"; break; \
  case 1: return "SLOT_S"; break; \
  case 2: return "SLOT_MULTILINECOMMENT"; break; \
  case 3: return "SLOT_COMMENT"; break; \
  case 4: return "SLOT_END"; break; \
  case 5: return "SLOT_DEFINITION"; break; \
  case 6: return "SLOT_SINGLE_EXPRESSION"; break; \
  case 7: return "SLOT_RULE"; break; \
  case 8: return "SLOT_EXPRESSION"; break; \
  case 9: return "SLOT_ALTERNATIVES"; break; \
  case 10: return "SLOT_TERMS"; break; \
  case 11: return "SLOT_TERM"; break; \
  case 12: return "SLOT_SCANMATCHER"; break; \
  case 13: return "SLOT_QUANTIFIEDMATCHER"; break; \
  case 14: return "SLOT_QUANTIFIER"; break; \
  case 15: return "SLOT_Q_ZEROORONE"; break; \
  case 16: return "SLOT_Q_ONEORMORE"; break; \
  case 17: return "SLOT_Q_ZEROORMORE"; break; \
  case 18: return "SLOT_Q_FROMTO"; break; \
  case 19: return "SLOT_Q_FROMTO_1"; break; \
  case 20: return "SLOT_Q_FROMTO_2"; break; \
  case 21: return "SLOT_Q_UNTIL"; break; \
  case 22: return "SLOT_Q_UNTIL_1"; break; \
  case 23: return "SLOT_Q_FROM"; break; \
  case 24: return "SLOT_Q_FROM_1"; break; \
  case 25: return "SLOT_Q_SPECIFIC"; break; \
  case 26: return "SLOT_Q_SPECIFIC_1"; break; \
  case 27: return "SLOT_Q_VAR"; break; \
  case 28: return "SLOT_MATCHER"; break; \
  case 29: return "SLOT_BITMASK"; break; \
  case 30: return "SLOT_VARCAPTURE"; break; \
  case 31: return "SLOT_CAPTURETYPE"; break; \
  case 32: return "SLOT_TYPE"; break; \
  case 33: return "SLOT_CAPTURE"; break; \
  case 34: return "SLOT_GROUP"; break; \
  case 35: return "SLOT_CAPTUREEND"; break; \
  case 36: return "SLOT_SET"; break; \
  case 37: return "SLOT_SET_NRTV"; break; \
  case 38: return "SLOT_SET_NRTV_1"; break; \
  case 39: return "SLOT_SET_NRTV_2"; break; \
  case 40: return "SLOT_VARREFERENCE"; break; \
  case 41: return "SLOT_MASK"; break; \
  case 42: return "SLOT_MASK_AFAF"; break; \
  case 43: return "SLOT_REFERENCE"; break; \
  case 44: return "SLOT_LIMITEDCALL"; break; \
  case 45: return "SLOT_LCMODES"; break; \
  case 46: return "SLOT_LCPARAM"; break; \
  case 47: return "SLOT_REPLACE"; break; \
  case 48: return "SLOT_REPLACETERMS"; break; \
  case 49: return "SLOT_REPLACETERM"; break; \
  case 50: return "SLOT_RECYCLE"; break; \
  case 51: return "SLOT_LEFTARROW"; break; \
  case 52: return "SLOT_RIGHTARROW"; break; \
  case 53: return "SLOT_FATARROW"; break; \
  case 54: return "SLOT_NOT"; break; \
  case 55: return "SLOT_AND"; break; \
  case 56: return "SLOT_MACRO"; break; \
  case 57: return "SLOT_ENDFORCE"; break; \
  case 58: return "SLOT_HEXLITERAL"; break; \
  case 59: return "SLOT_NUMBER"; break; \
  case 60: return "SLOT_STRING"; break; \
  case 61: return "SLOT_OR"; break; \
  case 62: return "SLOT_ANY"; break; \
  case 63: return "SLOT_SETNOT"; break; \
  case 64: return "SLOT_IMPORTDECL"; break; \
  case 65: return "SLOT_TYPEDECL"; break; \
  case 66: return "SLOT_FUNCDECL"; break; \
  case 67: return "SLOT_FUNCPARAMDECL"; break; \
  case 68: return "SLOT_PARAMDECL"; break; \
  case 69: return "SLOT_FUNCBODY"; break; \
  case 70: return "SLOT_GLOBALVARDECL"; break; \
  case 71: return "SLOT_FUNCSTMT"; break; \
  case 72: return "SLOT_BLOCKSTMT"; break; \
  case 73: return "SLOT_ST_IF"; break; \
  case 74: return "SLOT_CONDITION"; break; \
  case 75: return "SLOT_BLOCK"; break; \
  case 76: return "SLOT_IF_ELSIF"; break; \
  case 77: return "SLOT_IF_ELSE"; break; \
  case 78: return "SLOT_ST_WHILE"; break; \
  case 79: return "SLOT_ST_CATCH"; break; \
  case 80: return "SLOT_ST_RETURN"; break; \
  case 81: return "SLOT_ST_LOOPCTL"; break; \
  case 82: return "SLOT_VARDECL"; break; \
  case 83: return "SLOT_ASSIGNMENT"; break; \
  case 84: return "SLOT_SCR_TYPE"; break; \
  case 85: return "SLOT_SCR_EXPRESSION"; break; \
  case 86: return "SLOT_BINOP_P12"; break; \
  case 87: return "SLOT_BINOP_P11"; break; \
  case 88: return "SLOT_BINOP_P10"; break; \
  case 89: return "SLOT_BINOP_P09"; break; \
  case 90: return "SLOT_BINOP_P08"; break; \
  case 91: return "SLOT_BINOP_P07"; break; \
  case 92: return "SLOT_BINOP_P06"; break; \
  case 93: return "SLOT_BINOP_P05"; break; \
  case 94: return "SLOT_BINOP_P04"; break; \
  case 95: return "SLOT_BINOP_P03"; break; \
  case 96: return "SLOT_UNOP"; break; \
  case 97: return "SLOT_SCR_TERM"; break; \
  case 98: return "SLOT_SCR_UREFERENCE"; break; \
  case 99: return "SLOT_FUNCTIONCALL"; break; \
  case 100: return "SLOT_ARGSLIST"; break; \
  case 101: return "SLOT_SCR_REFERENCE"; break; \
  case 102: return "SLOT_INDEX"; break; \
  case 103: return "SLOT_LITERAL"; break; \
  case 104: return "SLOT_STRINGLITERAL"; break; \
  case 105: return "SLOT_STRINGLITERAL_NRTV"; break; \
  case 106: return "SLOT_LISTLITERAL"; break; \
  case 107: return "SLOT_LISTELT"; break; \
  case 108: return "SLOT_FLOATLITERAL"; break; \
  case 109: return "SLOT_INTLITERAL"; break; \
  case 110: return "SLOT_BOOLEANLITERAL"; break; \
  case 111: return "SLOT_KW_IMPORT"; break; \
  case 112: return "SLOT_KW_TYPE"; break; \
  case 113: return "SLOT_KW_FUNCTION"; break; \
  case 114: return "SLOT_KW_VAR"; break; \
  case 115: return "SLOT_KW_WHILE"; break; \
  case 116: return "SLOT_KW_RETURN"; break; \
  case 117: return "SLOT_KW_IF"; break; \
  case 118: return "SLOT_KW_ELSIF"; break; \
  case 119: return "SLOT_KW_ELSE"; break; \
  case 120: return "SLOT_KW_BREAK"; break; \
  case 121: return "SLOT_KW_CONTINUE"; break; \
  case 122: return "SLOT_KW_CATCH"; break; \
  case 123: return "SLOT_IDENT"; break; \
  case 124: return "SLOT_BOPEN"; break; \
  case 125: return "SLOT_BCLOSE"; break; \
  case 126: return "SLOT_CBOPEN"; break; \
  case 127: return "SLOT_CBCLOSE"; break; \
  case 128: return "SLOT_ABOPEN"; break; \
  case 129: return "SLOT_ABCLOSE"; break; \
  case 130: return "SLOT_ASSIGN"; break; \
  case 131: return "SLOT_EQUALS"; break; \
  case 132: return "SLOT_NEQUALS"; break; \
  case 133: return "SLOT_LT"; break; \
  case 134: return "SLOT_GT"; break; \
  case 135: return "SLOT_LTEQ"; break; \
  case 136: return "SLOT_GTEQ"; break; \
  case 137: return "SLOT_SEMICOLON"; break; \
  case 138: return "SLOT_COLON"; break; \
  case 139: return "SLOT_POW"; break; \
  case 140: return "SLOT_MUL"; break; \
  case 141: return "SLOT_DIV"; break; \
  case 142: return "SLOT_ADD"; break; \
  case 143: return "SLOT_SUB"; break; \
  case 144: return "SLOT_LOGAND"; break; \
  case 145: return "SLOT_LOGOR"; break; \
  case 146: return "SLOT_LOGNOT"; break; \
  case 147: return "SLOT_BITAND"; break; \
  case 148: return "SLOT_BITOR"; break; \
  case 149: return "SLOT_BITXOR"; break; \
  case 150: return "SLOT_BITNOT"; break; \
  case 151: return "SLOT_COMMA"; break; \
  case 152: return "SLOT_DOT"; break; \
  case 153: return "SLOT_LSHIFT"; break; \
  case 154: return "SLOT_RSHIFT"; break; \


#endif
