/**
* \file
* \brief This file is an autogenerated function prototypes header file.
*
* Copyright 2018 K.J. Hermans
* WARNING: This file is automatically generated. Any changes will be lost.
*/

#ifndef _NAIC_FUNCTIONS_FUNCTIONS_H_
#define _NAIC_FUNCTIONS_FUNCTIONS_H_

/* declared in ./naic_compile.c */
extern
NAIG_ERR_T naic_compile
  (naic_t* naic)
  __attribute__ ((warn_unused_result));

/* declared in ./naic_init.c */
extern
NAIG_ERR_T naic_init
  (naic_t* naic, char* grammar)
  __attribute__ ((warn_unused_result));

/* declared in ./naic_init.c */
extern
NAIG_ERR_T naic_set_grammar
  (naic_t* naic, char* grammar)
  __attribute__ ((warn_unused_result));

/* declared in ./naic_init.c */
extern
NAIG_ERR_T naic_set_output
  (naic_t* naic, FILE* file)
  __attribute__ ((warn_unused_result));

/* declared in ./naic_init.c */
extern
void naic_free
  (naic_t* naic);

/* declared in ./naic_nsp_init.c */
extern
NAIG_ERR_T naic_nsp_init
  (naic_nsp_t* nsp, char* name)
  __attribute__ ((warn_unused_result));

/* declared in ./naic_nsp_init.c */
extern
NAIG_ERR_T naic_nsp_new
  (naic_nsp_t** nsp, char* name)
  __attribute__ ((warn_unused_result));

/* declared in ./naic_nsp_init.c */
extern
void naic_nsp_free
  (naic_nsp_t* nsp);



#endif