#!/usr/bin/perl

##
##
##  Tool that generates bytecode from IPEG assembly
##
##  Usage: $0 (inputfile / '-') (outputfile / '-')
##
##
##

use Data::Dumper;

my $inputfile = shift @ARGV || '-';
my $outputfile = shift @ARGV || '-';

my ($in, $out);

if ($inputfile eq '-') {
  $in = *STDIN;
} else {
  open $in, '<', $inputfile || die "Could not open $inputfile";
}

my $input;
{
  while (my $line = <$in>) {
    $input .= $line;
  }
  close $in;
}

if ($outputfile eq '-') {
  $out = *STDOUT;
} else {
  open $out, '>', $outputfile || die "Could not open $outputfile";
}

use IPEG::Optimizer;

my $optimizer = IPEG::Optimizer->new($input);
my $aout = $optimizer->get_assembly();

syswrite $out, $aout;
close $out;

exit 0;

1;
