all: 
	@perl ./generate.pl \
		../../instructions.pl \
		../grammar/grammar.byc \
		../grammar/assembly.byc \
		../grammar/optimizer.byc \
		../grammar/optimizer.byc.labelmap \
		./include/

clean:

superclean:
	@rm -rf ./include/*
