/**
* \file
* \brief This file is an autogenerated function prototypes header file.
*
* Copyright 2018 K.J. Hermans
* WARNING: This file is automatically generated. Any changes will be lost.
*/

#ifndef ___LIB_NAIGAMA_FUNCTIONS_H_
#define ___LIB_NAIGAMA_FUNCTIONS_H_



#endif