#ifndef _SLOTMAP_H_
#define _SLOTMAP_H_

// names
#define SLOTMAP_INSTR_ANY 0
#define SLOTMAP_INSTR_BACKCOMMIT 1
#define SLOTMAP_INSTR_CALL 2
#define SLOTMAP_INSTR_CATCH 3
#define SLOTMAP_INSTR_CHAR 4
#define SLOTMAP_INSTR_CLOSECAPTURE 5
#define SLOTMAP_INSTR_COMMIT 6
#define SLOTMAP_INSTR_CONDJUMP 7
#define SLOTMAP_INSTR_COUNTER 8
#define SLOTMAP_INSTR_END 9
#define SLOTMAP_INSTR_ENDISOLATE 10
#define SLOTMAP_INSTR_ENDREPLACE 11
#define SLOTMAP_INSTR_FAIL 12
#define SLOTMAP_INSTR_FAILTWICE 13
#define SLOTMAP_INSTR_INTRPCAPTURE 14
#define SLOTMAP_INSTR_ISOLATE 15
#define SLOTMAP_INSTR_JUMP 16
#define SLOTMAP_INSTR_MASKEDCHAR 17
#define SLOTMAP_INSTR_NOOP 18
#define SLOTMAP_INSTR_OPENCAPTURE 19
#define SLOTMAP_INSTR_PARTIALCOMMIT 20
#define SLOTMAP_INSTR_QUAD 21
#define SLOTMAP_INSTR_RANGE 22
#define SLOTMAP_INSTR_REPLACE 23
#define SLOTMAP_INSTR_RET 24
#define SLOTMAP_INSTR_SET 25
#define SLOTMAP_INSTR_SKIP 26
#define SLOTMAP_INSTR_SPAN 27
#define SLOTMAP_INSTR_TESTANY 28
#define SLOTMAP_INSTR_TESTCHAR 29
#define SLOTMAP_INSTR_TESTQUAD 30
#define SLOTMAP_INSTR_TESTSET 31
#define SLOTMAP_INSTR_TRAP 32
#define SLOTMAP_INSTR_VAR 33


// slots

#define SLOTMAPLIST \
  "INSTR_ANY", \
  "INSTR_BACKCOMMIT", \
  "INSTR_CALL", \
  "INSTR_CATCH", \
  "INSTR_CHAR", \
  "INSTR_CLOSECAPTURE", \
  "INSTR_COMMIT", \
  "INSTR_CONDJUMP", \
  "INSTR_COUNTER", \
  "INSTR_END", \
  "INSTR_ENDISOLATE", \
  "INSTR_ENDREPLACE", \
  "INSTR_FAIL", \
  "INSTR_FAILTWICE", \
  "INSTR_INTRPCAPTURE", \
  "INSTR_ISOLATE", \
  "INSTR_JUMP", \
  "INSTR_MASKEDCHAR", \
  "INSTR_NOOP", \
  "INSTR_OPENCAPTURE", \
  "INSTR_PARTIALCOMMIT", \
  "INSTR_QUAD", \
  "INSTR_RANGE", \
  "INSTR_REPLACE", \
  "INSTR_RET", \
  "INSTR_SET", \
  "INSTR_SKIP", \
  "INSTR_SPAN", \
  "INSTR_TESTANY", \
  "INSTR_TESTCHAR", \
  "INSTR_TESTQUAD", \
  "INSTR_TESTSET", \
  "INSTR_TRAP", \
  "INSTR_VAR"


#endif
