/** Autogenerated from ./precomp/builtins.pl **/

#ifndef _NAIG_BUILTIN_H_
#define _NAIG_BUILTIN_H_

#define NAIG_BUILTIN_ERROR 1
#define NAIG_BUILTIN_PRINT 2
#define NAIG_BUILTIN_READ 3

#define NAIG_BUILTIN_ERROR_STRING "error"
#define NAIG_BUILTIN_PRINT_STRING "print"
#define NAIG_BUILTIN_READ_STRING "read"

#define NAIG_BUILTIN_STRINGS 3
#define NAIG_BUILTIN_STRING { \
  "error", \
  "print", \
  "read" \
}

#endif
