[package]
name = "naigama_global"
version = "0.1.0"
authors = ["kees"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "libnaig"
path = "src/lib.rs"
