#define OPTSLOTMAP_SWITCH \
  case 0: return "CHAR2QUAD_CHARSHEXBYTESCHARSHEXB"; break; \
  case 1: return "CHAR2QUAD_HEXBYTE"; break; \
  case 2: return "CHAR2QUAD_HEXBYTE_1"; break; \
  case 3: return "CHAR2QUAD_HEXBYTE_2"; break; \
  case 4: return "CHAR2QUAD_HEXBYTE_3"; break; \


#define OPTSLOT_CHAR2QUAD_CHARSHEXBYTESCHARSHEXB 0
#define OPTSLOT_CHAR2QUAD_HEXBYTE 1
#define OPTSLOT_CHAR2QUAD_HEXBYTE_1 2
#define OPTSLOT_CHAR2QUAD_HEXBYTE_2 3
#define OPTSLOT_CHAR2QUAD_HEXBYTE_3 4
