/**
* \file
* \brief This file is an autogenerated function prototypes header file.
*
* Copyright 2018 K.J. Hermans
* WARNING: This file is automatically generated. Any changes will be lost.
*/

#ifndef __HOME_WORK_WORK_NAIGAMA_SRC_GEN3_LIB_PROCESSOR__FUNCTIONS_H_
#define __HOME_WORK_WORK_NAIGAMA_SRC_GEN3_LIB_PROCESSOR__FUNCTIONS_H_

/* declared in /home/work/work/naigama/src/gen3/lib/processor//naip_add.c */
extern
NAIG_ERR_T naip_add
  (naip_stent_t* term1, naip_stent_t* term2, naip_stent_t* outcome)
  __attribute__ ((warn_unused_result));

/* declared in /home/work/work/naigama/src/gen3/lib/processor//naip_bitand.c */
extern
NAIG_ERR_T naip_bitand
  (naip_stent_t* term1, naip_stent_t* term2, naip_stent_t* outcome)
  __attribute__ ((warn_unused_result));

/* declared in /home/work/work/naigama/src/gen3/lib/processor//naip_copy.c */
extern
NAIG_ERR_T naip_copy
  (naip_stent_t* source, naip_stent_t* target)
  __attribute__ ((warn_unused_result));

/* declared in /home/work/work/naigama/src/gen3/lib/processor//naip_float.c */
extern
void naip_float
  (naip_stent_t* target, double value);

/* declared in /home/work/work/naigama/src/gen3/lib/processor//naip_int.c */
extern
void naip_int
  (naip_stent_t* target, int64_t value);

/* declared in /home/work/work/naigama/src/gen3/lib/processor//naip_istrue.c */
extern
int naip_istrue
  (naip_stent_t* term)
  __attribute__ ((warn_unused_result));

/* declared in /home/work/work/naigama/src/gen3/lib/processor//naip_loop.c */
extern
NAIG_ERR_T naip_loop
  (naip_t* engine)
  __attribute__ ((warn_unused_result));



#endif