stage_8:
	@cd engine && make
	@cd compiler && make
	@cd assembler && make
	@cd disassembler && make
	@cd naigama && make

clean:
	@cd engine && make clean
	@cd compiler && make clean
	@cd assembler && make clean
	@cd disassembler && make clean
	@cd naigama && make clean

superclean: clean
