all:
	cd util && make
	cd prevgen && make
	cd naigama && make
	cd engine && make
	cd compiler && make

clean:
	cd util && make clean
	cd prevgen && make clean
	cd naigama && make clean
	cd engine && make clean
	cd compiler && make clean
