all:
	cd util && make
	cd parser && make
	cd naigama && make
	cd engine && make
	cd compiler && make
	cd assembler && make

curgen:
	cd disassembler && make

clean:
	cd util && make clean
	cd parser && make clean
	cd naigama && make clean
	cd engine && make clean
	cd compiler && make clean
	cd assembler && make clean
	cd disassembler && make clean
