/**
* \file
* \brief This file is an autogenerated function prototypes header file.
*
* Copyright 2018 K.J. Hermans
* WARNING: This file is automatically generated. Any changes will be lost.
*/

#ifndef ___LIB_MEMIO_FUNCTIONS_H_
#define ___LIB_MEMIO_FUNCTIONS_H_

#include <stdio.h>
/* declared in ./lib/memio/naio_buf_write_bin.c */
extern
NAIG_ERR_T naio_buf_write_bin
  (naio_buf_t* buf, void* ptr, unsigned size)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/memio/naio_buf_write_string.c */
extern
NAIG_ERR_T naio_buf_write_string
  (naio_buf_t* buf, char* fmt, ...)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/memio/naio_labelmap_debug.c */
extern
NAIG_ERR_T naie_labelmap_debug
  (naio_labelmap_t* map)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/memio/naio_labelmap_get.c */
extern
NAIG_ERR_T naio_labelmap_get
  (naio_labelmap_t* map, char* str, unsigned len, unsigned* offset)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/memio/naio_labelmap_load.c */
extern
NAIG_ERR_T naio_labelmap_load
  (
    naio_labelmap_t* map,
    const char* filename
  )
  __attribute__ ((warn_unused_result));

/* declared in ./lib/memio/naio_labelmap_put.c */
extern
NAIG_ERR_T naio_labelmap_put
  (naio_labelmap_t* map, char* str, unsigned len, unsigned offset)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/memio/naio_labelmap_reverse.c */
extern
char* naio_labelmap_reverse
  (
    naio_labelmap_t* map,
    uint32_t offset
  )
  __attribute__ ((warn_unused_result));

/* declared in ./lib/memio/naio_labelmap_write.c */
extern
NAIG_ERR_T naio_labelmap_write
  (naio_labelmap_t* map, FILE* file)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/memio/naio_result_debug.c */
extern
void naio_result_debug
  (naio_result_t* result, unsigned char* data);

/* declared in ./lib/memio/naio_result_object.c */
extern
naio_resobj_t* naio_result_object
  (
    const unsigned char* input,
    unsigned inputlength,
    naio_result_t* result
  )
  __attribute__ ((warn_unused_result));

/* declared in ./lib/memio/naio_result_object_clean.c */
extern
void naio_result_object_clean
  (naio_resobj_t* object, unsigned slot);

/* declared in ./lib/memio/naio_result_object_debug.c */
extern
void naio_result_object_debug_
  (naio_resobj_t* object, char*(*fnc)(unsigned), unsigned indent);

/* declared in ./lib/memio/naio_result_object_debug.c */
extern
void naio_result_object_debug
  (naio_resobj_t* object, char*(*fnc)(unsigned));

/* declared in ./lib/memio/naio_result_object_free.c */
extern
void naio_result_object_free
  (naio_resobj_t* object);

/* declared in ./lib/memio/naio_result_object_iterate.c */
extern
NAIG_ERR_T naio_result_object_iterate
  (naio_resobj_t* resobj, unsigned nelts, naio_resobj_itelt_t* elts)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/memio/naio_result_object_path.c */
extern
naio_resobj_t* naio_result_object_path
  (naio_resobj_t* parent, unsigned nargs, ...)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/memio/naio_result_object_query.c */
extern
naio_resobj_t* naio_result_object_query
  (naio_resobj_t* parent, unsigned nargs, ...)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/memio/naio_slotmap_add.c */
extern
NAIG_ERR_T naio_slotmap_add
  (
    naio_slotmap_t* slotmap,
    char* name,
    unsigned slot
  )
  __attribute__ ((warn_unused_result));

/* declared in ./lib/memio/naio_slotmap_add_capture.c */
extern
NAIG_ERR_T naio_slotmap_add_capture
  (
    naio_slotmap_t* slotmap,
    naio_resobj_t* rule,
    naio_resobj_t* capture,
    unsigned slot
  )
  __attribute__ ((warn_unused_result));

/* declared in ./lib/memio/naio_slotmap_debug.c */
extern
void naio_slotmap_debug
  (naio_slotmap_t* slotmap);

/* declared in ./lib/memio/naio_slotmap_get.c */
extern
NAIG_ERR_T naio_slotmap_get
  (
    naio_slotmap_t* slotmap,
    char* slotname,
    unsigned* slot
  )
  __attribute__ ((warn_unused_result));

/* declared in ./lib/memio/naio_slotmap_load.c */
extern
NAIG_ERR_T naio_slotmap_load
  (char* path, naio_slotmap_t* slotmap)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/memio/naio_slotmap_query.c */
extern
unsigned naio_slotmap_query
  (
    naio_slotmap_t* slotmap,
    char* slotname
  )
  __attribute__ ((warn_unused_result));

/* declared in ./lib/memio/naio_slotmap_string.c */
extern
char* naio_slotmap_string
  (naio_slotmap_t* slotmap, unsigned slot)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/memio/naio_slotmap_write.c */
extern
NAIG_ERR_T naio_slotmap_write
  (naio_slotmap_t* slotmap, FILE* out)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/memio/naio_slotmap_write_h.c */
extern
NAIG_ERR_T naio_slotmap_write_h
  (naio_slotmap_t* slotmap, FILE* out)
  __attribute__ ((warn_unused_result));



#endif