/**
* \file
* \brief This file is an autogenerated function prototypes header file.
*
* Copyright 2018 K.J. Hermans
* WARNING: This file is automatically generated. Any changes will be lost.
*/

#ifndef ___LIB_NAIGAMA_FUNCTIONS_H_
#define ___LIB_NAIGAMA_FUNCTIONS_H_

#include "naig_types.h"
#include "naigama_types.h"
/* declared in ./lib/naigama/naig_compile.c */
extern
NAIG_ERR_T naig_compile
  (naig_t* naig, char* grammar, int traps)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/naigama/naig_replace.c */
extern
NAIG_ERR_T naig_replace
  (
    naig_t* naig,
    unsigned char* input,
    unsigned input_length,
    naie_result_t* result,
    unsigned char** output,
    unsigned* output_length
  )
  __attribute__ ((warn_unused_result));

/* declared in ./lib/naigama/naig_replace_size.c */
extern
int naig_replace_size
  (naie_result_t* result)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/naigama/naig_run.c */
extern
NAIG_ERR_T naig_run
  (
    naig_t* naig,
    unsigned char* input,
    unsigned input_length,
    naie_result_t* result
  )
  __attribute__ ((warn_unused_result));



#endif