-- Generated by (Xgen) ipeg_compile at Sat Apr 18 15:29:04 2020
  call TOP
  end
TOP:
  call INSTRUCTIONS
  ret
S:
  set 0026000001000000000000000000000000000000000000000000000000000000
  catch S_7_INDEF
S_7_LOOP:
  set 0026000001000000000000000000000000000000000000000000000000000000
  partialcommit S_7_LOOP
S_7_INDEF:
  ret
__prefix:
  catch __prefix_11_INDEF
__prefix_11_LOOP:
  catch __prefix_FAILURE_12
  char 2d
  char 2d
  catch __prefix_20_INDEF
__prefix_20_LOOP:
  set fffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
  partialcommit __prefix_20_LOOP
__prefix_20_INDEF:
  char 0a
  commit __prefix_SUCCESS_11
__prefix_FAILURE_12:
  set 0026000001000000000000000000000000000000000000000000000000000000
  catch __prefix_27_INDEF
__prefix_27_LOOP:
  set 0026000001000000000000000000000000000000000000000000000000000000
  partialcommit __prefix_27_LOOP
__prefix_27_INDEF:
__prefix_SUCCESS_11:
  partialcommit __prefix_11_LOOP
__prefix_11_INDEF:
  ret
INSTRUCTIONS:
  call __prefix
  call INSTRUCTION
  catch INSTRUCTIONS_31_INDEF
INSTRUCTIONS_31_LOOP:
  call INSTRUCTION
  partialcommit INSTRUCTIONS_31_LOOP
INSTRUCTIONS_31_INDEF:
  call END
  ret
INSTRUCTION:
  call __prefix
  opencapture 0
  catch INSTRUCTION_FAILURE_38
  call ANYINSTR
  commit INSTRUCTION_SUCCESS_37
INSTRUCTION_FAILURE_38:
  catch INSTRUCTION_FAILURE_43
  call BACKCOMMITINSTR
  commit INSTRUCTION_SUCCESS_42
INSTRUCTION_FAILURE_43:
  catch INSTRUCTION_FAILURE_48
  call CALLINSTR
  commit INSTRUCTION_SUCCESS_47
INSTRUCTION_FAILURE_48:
  catch INSTRUCTION_FAILURE_53
  call CATCHINSTR
  commit INSTRUCTION_SUCCESS_52
INSTRUCTION_FAILURE_53:
  catch INSTRUCTION_FAILURE_58
  call CHARINSTR
  commit INSTRUCTION_SUCCESS_57
INSTRUCTION_FAILURE_58:
  catch INSTRUCTION_FAILURE_63
  call MASKEDCHARINSTR
  commit INSTRUCTION_SUCCESS_62
INSTRUCTION_FAILURE_63:
  catch INSTRUCTION_FAILURE_68
  call CLOSECAPTUREINSTR
  commit INSTRUCTION_SUCCESS_67
INSTRUCTION_FAILURE_68:
  catch INSTRUCTION_FAILURE_73
  call COMMITINSTR
  commit INSTRUCTION_SUCCESS_72
INSTRUCTION_FAILURE_73:
  catch INSTRUCTION_FAILURE_78
  call STARTREPLACEINSTR
  commit INSTRUCTION_SUCCESS_77
INSTRUCTION_FAILURE_78:
  catch INSTRUCTION_FAILURE_83
  call ENDREPLACEINSTR
  commit INSTRUCTION_SUCCESS_82
INSTRUCTION_FAILURE_83:
  catch INSTRUCTION_FAILURE_88
  call REPLACEINSTR
  commit INSTRUCTION_SUCCESS_87
INSTRUCTION_FAILURE_88:
  catch INSTRUCTION_FAILURE_93
  call ENDINSTR
  commit INSTRUCTION_SUCCESS_92
INSTRUCTION_FAILURE_93:
  catch INSTRUCTION_FAILURE_98
  call FAILTWICEINSTR
  commit INSTRUCTION_SUCCESS_97
INSTRUCTION_FAILURE_98:
  catch INSTRUCTION_FAILURE_103
  call FAILINSTR
  commit INSTRUCTION_SUCCESS_102
INSTRUCTION_FAILURE_103:
  catch INSTRUCTION_FAILURE_108
  call JUMPINSTR
  commit INSTRUCTION_SUCCESS_107
INSTRUCTION_FAILURE_108:
  catch INSTRUCTION_FAILURE_113
  call NOOPINSTR
  commit INSTRUCTION_SUCCESS_112
INSTRUCTION_FAILURE_113:
  catch INSTRUCTION_FAILURE_118
  call TRAPINSTR
  commit INSTRUCTION_SUCCESS_117
INSTRUCTION_FAILURE_118:
  catch INSTRUCTION_FAILURE_123
  call OPENCAPTUREINSTR
  commit INSTRUCTION_SUCCESS_122
INSTRUCTION_FAILURE_123:
  catch INSTRUCTION_FAILURE_128
  call PARTIALCOMMITINSTR
  commit INSTRUCTION_SUCCESS_127
INSTRUCTION_FAILURE_128:
  catch INSTRUCTION_FAILURE_133
  call QUADINSTR
  commit INSTRUCTION_SUCCESS_132
INSTRUCTION_FAILURE_133:
  catch INSTRUCTION_FAILURE_138
  call RETINSTR
  commit INSTRUCTION_SUCCESS_137
INSTRUCTION_FAILURE_138:
  catch INSTRUCTION_FAILURE_143
  call SETINSTR
  commit INSTRUCTION_SUCCESS_142
INSTRUCTION_FAILURE_143:
  catch INSTRUCTION_FAILURE_148
  call RANGEINSTR
  commit INSTRUCTION_SUCCESS_147
INSTRUCTION_FAILURE_148:
  catch INSTRUCTION_FAILURE_153
  call SKIPINSTR
  commit INSTRUCTION_SUCCESS_152
INSTRUCTION_FAILURE_153:
  catch INSTRUCTION_FAILURE_158
  call SPANINSTR
  commit INSTRUCTION_SUCCESS_157
INSTRUCTION_FAILURE_158:
  catch INSTRUCTION_FAILURE_163
  call TESTANYINSTR
  commit INSTRUCTION_SUCCESS_162
INSTRUCTION_FAILURE_163:
  catch INSTRUCTION_FAILURE_168
  call TESTCHARINSTR
  commit INSTRUCTION_SUCCESS_167
INSTRUCTION_FAILURE_168:
  catch INSTRUCTION_FAILURE_173
  call TESTQUADINSTR
  commit INSTRUCTION_SUCCESS_172
INSTRUCTION_FAILURE_173:
  catch INSTRUCTION_FAILURE_178
  call TESTSETINSTR
  commit INSTRUCTION_SUCCESS_177
INSTRUCTION_FAILURE_178:
  catch INSTRUCTION_FAILURE_183
  call VARINSTR
  commit INSTRUCTION_SUCCESS_182
INSTRUCTION_FAILURE_183:
  catch INSTRUCTION_FAILURE_188
  call COUNTERINSTR
  commit INSTRUCTION_SUCCESS_187
INSTRUCTION_FAILURE_188:
  catch INSTRUCTION_FAILURE_193
  call CONDJUMPINSTR
  commit INSTRUCTION_SUCCESS_192
INSTRUCTION_FAILURE_193:
  call LABELDEF
INSTRUCTION_SUCCESS_192:
INSTRUCTION_SUCCESS_187:
INSTRUCTION_SUCCESS_182:
INSTRUCTION_SUCCESS_177:
INSTRUCTION_SUCCESS_172:
INSTRUCTION_SUCCESS_167:
INSTRUCTION_SUCCESS_162:
INSTRUCTION_SUCCESS_157:
INSTRUCTION_SUCCESS_152:
INSTRUCTION_SUCCESS_147:
INSTRUCTION_SUCCESS_142:
INSTRUCTION_SUCCESS_137:
INSTRUCTION_SUCCESS_132:
INSTRUCTION_SUCCESS_127:
INSTRUCTION_SUCCESS_122:
INSTRUCTION_SUCCESS_117:
INSTRUCTION_SUCCESS_112:
INSTRUCTION_SUCCESS_107:
INSTRUCTION_SUCCESS_102:
INSTRUCTION_SUCCESS_97:
INSTRUCTION_SUCCESS_92:
INSTRUCTION_SUCCESS_87:
INSTRUCTION_SUCCESS_82:
INSTRUCTION_SUCCESS_77:
INSTRUCTION_SUCCESS_72:
INSTRUCTION_SUCCESS_67:
INSTRUCTION_SUCCESS_62:
INSTRUCTION_SUCCESS_57:
INSTRUCTION_SUCCESS_52:
INSTRUCTION_SUCCESS_47:
INSTRUCTION_SUCCESS_42:
INSTRUCTION_SUCCESS_37:
  closecapture 0
  ret
END:
  call __prefix
  catch END_FAILURE_201
  any
  failtwice
END_FAILURE_201:
  ret
ANYINSTR:
  call __prefix
  opencapture 1
  char 61
  char 6e
  char 79
  closecapture 1
  ret
BACKCOMMITINSTR:
  call __prefix
  opencapture 2
  char 62
  char 61
  char 63
  char 6b
  char 63
  char 6f
  char 6d
  char 6d
  char 69
  char 74
  closecapture 2
  call S
  call LABEL
  ret
CALLINSTR:
  call __prefix
  opencapture 3
  char 63
  char 61
  char 6c
  char 6c
  closecapture 3
  call S
  call LABEL
  ret
CATCHINSTR:
  call __prefix
  opencapture 4
  char 63
  char 61
  char 74
  char 63
  char 68
  closecapture 4
  call S
  call LABEL
  ret
CHARINSTR:
  call __prefix
  opencapture 5
  char 63
  char 68
  char 61
  char 72
  closecapture 5
  call S
  call HEXBYTE
  ret
MASKEDCHARINSTR:
  call __prefix
  opencapture 6
  char 6d
  char 61
  char 73
  char 6b
  char 65
  char 64
  char 63
  char 68
  char 61
  char 72
  closecapture 6
  call S
  call HEXBYTE
  call S
  call HEXBYTE
  ret
CLOSECAPTUREINSTR:
  call __prefix
  opencapture 7
  char 63
  char 6c
  char 6f
  char 73
  char 65
  char 63
  char 61
  char 70
  char 74
  char 75
  char 72
  char 65
  closecapture 7
  call S
  call SLOT
  catch CLOSECAPTUREINSTR_290_MAX
  call S
  call TYPE
  partialcommit CLOSECAPTUREINSTR_290_PC
CLOSECAPTUREINSTR_290_PC:
  commit CLOSECAPTUREINSTR_290_MAX
CLOSECAPTUREINSTR_290_MAX:
  ret
COMMITINSTR:
  call __prefix
  opencapture 8
  char 63
  char 6f
  char 6d
  char 6d
  char 69
  char 74
  closecapture 8
  call S
  call LABEL
  ret
ENDINSTR:
  call __prefix
  opencapture 9
  char 65
  char 6e
  char 64
  closecapture 9
  catch ENDINSTR_317_MAX
  call S
  call CODE
  partialcommit ENDINSTR_317_PC
ENDINSTR_317_PC:
  commit ENDINSTR_317_MAX
ENDINSTR_317_MAX:
  ret
FAILINSTR:
  call __prefix
  opencapture 10
  char 66
  char 61
  char 69
  char 6c
  closecapture 10
  ret
FAILTWICEINSTR:
  call __prefix
  opencapture 11
  char 66
  char 61
  char 69
  char 6c
  char 74
  char 77
  char 69
  char 63
  char 65
  closecapture 11
  ret
JUMPINSTR:
  call __prefix
  opencapture 12
  char 6a
  char 75
  char 6d
  char 70
  closecapture 12
  call S
  call LABEL
  ret
NOOPINSTR:
  call __prefix
  opencapture 13
  char 6e
  char 6f
  char 6f
  char 70
  closecapture 13
  ret
TRAPINSTR:
  call __prefix
  opencapture 14
  char 74
  char 72
  char 61
  char 70
  closecapture 14
  ret
OPENCAPTUREINSTR:
  call __prefix
  opencapture 15
  char 6f
  char 70
  char 65
  char 6e
  char 63
  char 61
  char 70
  char 74
  char 75
  char 72
  char 65
  closecapture 15
  call S
  call SLOT
  ret
PARTIALCOMMITINSTR:
  call __prefix
  opencapture 16
  char 70
  char 61
  char 72
  char 74
  char 69
  char 61
  char 6c
  char 63
  char 6f
  char 6d
  char 6d
  char 69
  char 74
  closecapture 16
  call S
  call LABEL
  ret
QUADINSTR:
  call __prefix
  opencapture 17
  char 71
  char 75
  char 61
  char 64
  closecapture 17
  call S
  call QUAD
  ret
REPLACEINSTR:
  call __prefix
  opencapture 18
  char 72
  char 65
  char 70
  char 6c
  char 61
  char 63
  char 65
  closecapture 18
  call S
  call LABEL
  call S
  call LABEL
  ret
STARTREPLACEINSTR:
  call __prefix
  opencapture 19
  char 73
  char 74
  char 61
  char 72
  char 74
  char 72
  char 65
  char 70
  char 6c
  char 61
  char 63
  char 65
  closecapture 19
  ret
ENDREPLACEINSTR:
  call __prefix
  opencapture 20
  char 65
  char 6e
  char 64
  char 72
  char 65
  char 70
  char 6c
  char 61
  char 63
  char 65
  closecapture 20
  ret
RETINSTR:
  call __prefix
  opencapture 21
  char 72
  char 65
  char 74
  closecapture 21
  ret
SETINSTR:
  call __prefix
  opencapture 22
  char 73
  char 65
  char 74
  closecapture 22
  call S
  call SET
  ret
RANGEINSTR:
  call __prefix
  opencapture 23
  char 72
  char 61
  char 6e
  char 67
  char 65
  closecapture 23
  call S
  call NUMBER
  call S
  call NUMBER
  ret
SKIPINSTR:
  call __prefix
  opencapture 24
  char 73
  char 6b
  char 69
  char 70
  closecapture 24
  call S
  call NUMBER
  ret
SPANINSTR:
  call __prefix
  opencapture 25
  char 73
  char 70
  char 61
  char 6e
  closecapture 25
  call S
  call SET
  ret
TESTANYINSTR:
  call __prefix
  opencapture 26
  char 74
  char 65
  char 73
  char 74
  char 61
  char 6e
  char 79
  closecapture 26
  call S
  call LABEL
  ret
TESTCHARINSTR:
  call __prefix
  opencapture 27
  char 74
  char 65
  char 73
  char 74
  char 63
  char 68
  char 61
  char 72
  closecapture 27
  call S
  call HEXBYTE
  call S
  call LABEL
  catch TESTCHARINSTR_518_MAX
  call S
  call AMPERSAND
  call HEXBYTE
  partialcommit TESTCHARINSTR_518_PC
TESTCHARINSTR_518_PC:
  commit TESTCHARINSTR_518_MAX
TESTCHARINSTR_518_MAX:
  ret
TESTQUADINSTR:
  call __prefix
  opencapture 28
  char 74
  char 65
  char 73
  char 74
  char 71
  char 75
  char 61
  char 64
  closecapture 28
  call S
  call QUAD
  call S
  call LABEL
  ret
TESTSETINSTR:
  call __prefix
  opencapture 29
  char 74
  char 65
  char 73
  char 74
  char 73
  char 65
  char 74
  closecapture 29
  call S
  call SET
  call S
  call LABEL
  ret
VARINSTR:
  call __prefix
  opencapture 30
  char 76
  char 61
  char 72
  closecapture 30
  call S
  call SLOT
  ret
COUNTERINSTR:
  call __prefix
  opencapture 31
  char 63
  char 6f
  char 75
  char 6e
  char 74
  char 65
  char 72
  closecapture 31
  call S
  call REGISTER
  call S
  call NUMBER
  ret
CONDJUMPINSTR:
  call __prefix
  opencapture 32
  char 63
  char 6f
  char 6e
  char 64
  char 6a
  char 75
  char 6d
  char 70
  closecapture 32
  call S
  call REGISTER
  call S
  call LABEL
  ret
LABELDEF:
  call __prefix
  opencapture 33
  call LABEL
  closecapture 33
  call COLON
  ret
CODE:
  call __prefix
  call NUMBER
  ret
HEXBYTE:
  call __prefix
  opencapture 34
  counter 1 2
HEXBYTE_629_MINLOOP:
  set 000000000000ff037e0000007e00000000000000000000000000000000000000
  condjump 1 HEXBYTE_629_MINLOOP
  closecapture 34
  ret
LABEL:
  call __prefix
  opencapture 35
  set 000000000000ff03feffff87feffff0700000000000000000000000000000000
  catch LABEL_635_MAX
  counter 1 63
LABEL_635_EXTRALOOP:
  set 000000000000ff03feffff87feffff0700000000000000000000000000000000
  partialcommit LABEL_635_PC
LABEL_635_PC:
  condjump 1 LABEL_635_EXTRALOOP
  commit LABEL_635_MAX
LABEL_635_MAX:
  closecapture 35
  ret
NUMBER:
  call __prefix
  opencapture 36
  set 000000000000ff03000000000000000000000000000000000000000000000000
  catch NUMBER_642_INDEF
NUMBER_642_LOOP:
  set 000000000000ff03000000000000000000000000000000000000000000000000
  partialcommit NUMBER_642_LOOP
NUMBER_642_INDEF:
  closecapture 36
  ret
QUAD:
  call __prefix
  opencapture 37
  counter 2 8
QUAD_648_MINLOOP:
  set 000000000000ff037e0000007e00000000000000000000000000000000000000
  condjump 2 QUAD_648_MINLOOP
  closecapture 37
  ret
SET:
  call __prefix
  opencapture 38
  counter 3 64
SET_654_MINLOOP:
  set 000000000000ff037e0000007e00000000000000000000000000000000000000
  condjump 3 SET_654_MINLOOP
  closecapture 38
  ret
SLOT:
  call __prefix
  call NUMBER
  ret
REGISTER:
  call __prefix
  call NUMBER
  ret
TYPE:
  call __prefix
  call NUMBER
  ret
COLON:
  call __prefix
  char 3a
  ret
AMPERSAND:
  call __prefix
  char 26
  ret
STRING:
  call __prefix
  opencapture 39
  char 27
  catch STRING_679_INDEF
STRING_679_LOOP:
  catch STRING_FAILURE_680
  char 5c
  any
  commit STRING_SUCCESS_679
STRING_FAILURE_680:
  set ffffffff7fffffffffffffffffffffffffffffffffffffffffffffffffffffff
STRING_SUCCESS_679:
  partialcommit STRING_679_LOOP
STRING_679_INDEF:
  char 27
  closecapture 39
  ret

