#ifndef _SLOTMAP_GRAMMAR_H_
#define _SLOTMAP_GRAMMAR_H_

/* Generated by genslthdr in ./grammar/grammar.slotmap */

#define SLOT_GRAMMAR 0
#define SLOT_S 1
#define SLOT_MULTILINECOMMENT 2
#define SLOT_COMMENT 3
#define SLOT_END 4
#define SLOT_DEFINITION 5
#define SLOT_SINGLE_EXPRESSION 6
#define SLOT_RULE 7
#define SLOT_EXPRESSION 8
#define SLOT_ALTERNATIVES 9
#define SLOT_TERMS 10
#define SLOT_TERM 11
#define SLOT_SCANMATCHER 12
#define SLOT_QUANTIFIEDMATCHER 13
#define SLOT_QUANTIFIER 14
#define SLOT_Q_ZEROORONE 15
#define SLOT_Q_ONEORMORE 16
#define SLOT_Q_ZEROORMORE 17
#define SLOT_Q_FROMTO 18
#define SLOT_Q_FROMTO_1 19
#define SLOT_Q_FROMTO_2 20
#define SLOT_Q_UNTIL 21
#define SLOT_Q_UNTIL_1 22
#define SLOT_Q_FROM 23
#define SLOT_Q_FROM_1 24
#define SLOT_Q_SPECIFIC 25
#define SLOT_Q_SPECIFIC_1 26
#define SLOT_Q_VAR 27
#define SLOT_MATCHER 28
#define SLOT_BITMASK 29
#define SLOT_VARCAPTURE 30
#define SLOT_CAPTURETYPE 31
#define SLOT_TYPE 32
#define SLOT_CAPTURE 33
#define SLOT_GROUP 34
#define SLOT_CAPTUREEND 35
#define SLOT_SET 36
#define SLOT_SET_NRTV 37
#define SLOT_SET_NRTV_1 38
#define SLOT_SET_NRTV_2 39
#define SLOT_VARREFERENCE 40
#define SLOT_MASK 41
#define SLOT_MASK_AFAF 42
#define SLOT_REFERENCE 43
#define SLOT_LIMITEDCALL 44
#define SLOT_LCMODES 45
#define SLOT_LCPARAM 46
#define SLOT_REPLACE 47
#define SLOT_REPLACETERMS 48
#define SLOT_REPLACETERM 49
#define SLOT_RECYCLE 50
#define SLOT_LEFTARROW 51
#define SLOT_RIGHTARROW 52
#define SLOT_FATARROW 53
#define SLOT_NOT 54
#define SLOT_AND 55
#define SLOT_MACRO 56
#define SLOT_ENDFORCE 57
#define SLOT_HEXLITERAL 58
#define SLOT_NUMBER 59
#define SLOT_STRING 60
#define SLOT_OR 61
#define SLOT_ANY 62
#define SLOT_SETNOT 63
#define SLOT_IMPORTDECL 64
#define SLOT_KW_IMPORT 65
#define SLOT_OPTNAMESPACE 66
#define SLOT_KW_AS 67
#define SLOT_STRINGLITERAL 68
#define SLOT_STRINGLITERAL_NRTV 69
#define SLOT_IDENT 70
#define SLOT_BOPEN 71
#define SLOT_BCLOSE 72
#define SLOT_CBOPEN 73
#define SLOT_CBCLOSE 74
#define SLOT_ABOPEN 75
#define SLOT_ABCLOSE 76
#define SLOT_COLON 77
#define SLOT_SEMICOLON 78

#define _SLOTMAP_GRAMMAR_SWITCH \
  case 0: return "SLOT_GRAMMAR"; break; \
  case 1: return "SLOT_S"; break; \
  case 2: return "SLOT_MULTILINECOMMENT"; break; \
  case 3: return "SLOT_COMMENT"; break; \
  case 4: return "SLOT_END"; break; \
  case 5: return "SLOT_DEFINITION"; break; \
  case 6: return "SLOT_SINGLE_EXPRESSION"; break; \
  case 7: return "SLOT_RULE"; break; \
  case 8: return "SLOT_EXPRESSION"; break; \
  case 9: return "SLOT_ALTERNATIVES"; break; \
  case 10: return "SLOT_TERMS"; break; \
  case 11: return "SLOT_TERM"; break; \
  case 12: return "SLOT_SCANMATCHER"; break; \
  case 13: return "SLOT_QUANTIFIEDMATCHER"; break; \
  case 14: return "SLOT_QUANTIFIER"; break; \
  case 15: return "SLOT_Q_ZEROORONE"; break; \
  case 16: return "SLOT_Q_ONEORMORE"; break; \
  case 17: return "SLOT_Q_ZEROORMORE"; break; \
  case 18: return "SLOT_Q_FROMTO"; break; \
  case 19: return "SLOT_Q_FROMTO_1"; break; \
  case 20: return "SLOT_Q_FROMTO_2"; break; \
  case 21: return "SLOT_Q_UNTIL"; break; \
  case 22: return "SLOT_Q_UNTIL_1"; break; \
  case 23: return "SLOT_Q_FROM"; break; \
  case 24: return "SLOT_Q_FROM_1"; break; \
  case 25: return "SLOT_Q_SPECIFIC"; break; \
  case 26: return "SLOT_Q_SPECIFIC_1"; break; \
  case 27: return "SLOT_Q_VAR"; break; \
  case 28: return "SLOT_MATCHER"; break; \
  case 29: return "SLOT_BITMASK"; break; \
  case 30: return "SLOT_VARCAPTURE"; break; \
  case 31: return "SLOT_CAPTURETYPE"; break; \
  case 32: return "SLOT_TYPE"; break; \
  case 33: return "SLOT_CAPTURE"; break; \
  case 34: return "SLOT_GROUP"; break; \
  case 35: return "SLOT_CAPTUREEND"; break; \
  case 36: return "SLOT_SET"; break; \
  case 37: return "SLOT_SET_NRTV"; break; \
  case 38: return "SLOT_SET_NRTV_1"; break; \
  case 39: return "SLOT_SET_NRTV_2"; break; \
  case 40: return "SLOT_VARREFERENCE"; break; \
  case 41: return "SLOT_MASK"; break; \
  case 42: return "SLOT_MASK_AFAF"; break; \
  case 43: return "SLOT_REFERENCE"; break; \
  case 44: return "SLOT_LIMITEDCALL"; break; \
  case 45: return "SLOT_LCMODES"; break; \
  case 46: return "SLOT_LCPARAM"; break; \
  case 47: return "SLOT_REPLACE"; break; \
  case 48: return "SLOT_REPLACETERMS"; break; \
  case 49: return "SLOT_REPLACETERM"; break; \
  case 50: return "SLOT_RECYCLE"; break; \
  case 51: return "SLOT_LEFTARROW"; break; \
  case 52: return "SLOT_RIGHTARROW"; break; \
  case 53: return "SLOT_FATARROW"; break; \
  case 54: return "SLOT_NOT"; break; \
  case 55: return "SLOT_AND"; break; \
  case 56: return "SLOT_MACRO"; break; \
  case 57: return "SLOT_ENDFORCE"; break; \
  case 58: return "SLOT_HEXLITERAL"; break; \
  case 59: return "SLOT_NUMBER"; break; \
  case 60: return "SLOT_STRING"; break; \
  case 61: return "SLOT_OR"; break; \
  case 62: return "SLOT_ANY"; break; \
  case 63: return "SLOT_SETNOT"; break; \
  case 64: return "SLOT_IMPORTDECL"; break; \
  case 65: return "SLOT_KW_IMPORT"; break; \
  case 66: return "SLOT_OPTNAMESPACE"; break; \
  case 67: return "SLOT_KW_AS"; break; \
  case 68: return "SLOT_STRINGLITERAL"; break; \
  case 69: return "SLOT_STRINGLITERAL_NRTV"; break; \
  case 70: return "SLOT_IDENT"; break; \
  case 71: return "SLOT_BOPEN"; break; \
  case 72: return "SLOT_BCLOSE"; break; \
  case 73: return "SLOT_CBOPEN"; break; \
  case 74: return "SLOT_CBCLOSE"; break; \
  case 75: return "SLOT_ABOPEN"; break; \
  case 76: return "SLOT_ABCLOSE"; break; \
  case 77: return "SLOT_COLON"; break; \
  case 78: return "SLOT_SEMICOLON"; break; \


#endif
