/**
* \file
* \brief This file is an autogenerated function prototypes header file.
*
* Copyright 2018 K.J. Hermans
* WARNING: This file is automatically generated. Any changes will be lost.
*/

#ifndef ___LIB_COMPILER_FUNCTIONS_H_
#define ___LIB_COMPILER_FUNCTIONS_H_

/* declared in ./lib/compiler/naic_compile.c */
extern
NAIG_ERR_T naic_compile
  (
    char* grammar,
    naio_slotmap_t* slots,
    unsigned flags,
    char** paths,
    unsigned npaths,
    NAIG_ERR_T(*fnc)(void*,char*,...),
    void* arg
  )
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/naic_compile_top.c */
extern
NAIG_ERR_T naic_compile_top
  (naic_t* naic, naio_resobj_t* top)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/naic_grammar_slotmap_string.c */
extern
char* naic_grammar_slotmap_string
  (unsigned slot)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/naic_parsetree.c */
extern
NAIG_ERR_T naic_parsetree
  (
    char* grammar,
    naio_resobj_t** object,
    int debug
  )
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/naic_reserve.c */
extern
NAIG_ERR_T naic_reserve
  (naic_t* naic, char* fmt, ...)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/naic_resobj_debug.c */
extern
void naic_resobj_debug
  (naio_resobj_t* obj);

/* declared in ./lib/compiler/naic_sp.c */
extern
NAIG_ERR_T naic_sp
  (naic_t* naic, naio_resobj_t* top)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/namespace/naic_nsp_add.c */
extern
NAIG_ERR_T naic_nsp_add
  (naic_nspnod_t* nsp, naic_nspnod_t* entry)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/namespace/naic_nsp_add_block.c */
extern
NAIG_ERR_T naic_nsp_add_block
  (naic_nspnod_t* nsp, naio_resobj_t* object, naic_nspnod_t** block)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/namespace/naic_nsp_add_func.c */
extern
NAIG_ERR_T naic_nsp_add_func
  (naic_nspnod_t* nsp, char* name, naio_resobj_t* object, naic_nspnod_t** func)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/namespace/naic_nsp_add_global.c */
extern
NAIG_ERR_T naic_nsp_add_global
  (
    naic_nspnod_t* nsp,
    char* name,
    char* type,
    naio_resobj_t* object,
    naic_nspnod_t** var
  )
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/namespace/naic_nsp_add_rule.c */
extern
NAIG_ERR_T naic_nsp_add_rule
  (naic_nspnod_t* nsp, char* name, naio_resobj_t* object, naic_nspnod_t** rule)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/namespace/naic_nsp_add_rulevar.c */
extern
NAIG_ERR_T naic_nsp_add_rulevar
  (naic_nspnod_t* nsp, char* name, unsigned slot)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/namespace/naic_nsp_add_var.c */
extern
NAIG_ERR_T naic_nsp_add_var
  (
    naic_nspnod_t* nsp,
    char* name,
    char* type,
    naio_resobj_t* object,
    naic_nspnod_t** var
  )
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/namespace/naic_nsp_entry_new.c */
extern
NAIG_ERR_T naic_nsp_entry_new
  (
    naic_nspnod_t* parent,
    char* name,
    unsigned type,
    naio_resobj_t* object,
    naic_nspnod_t** result
  )
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/namespace/naic_nsp_free.c */
extern
void naic_nsp_free
  (naic_nspnod_t* nsp);

/* declared in ./lib/compiler/namespace/naic_nsp_function_update.c */
extern
NAIG_ERR_T naic_nsp_function_update
  (naic_nspnod_t* node)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/namespace/naic_nsp_get.c */
extern
NAIG_ERR_T naic_nsp_get
  (naic_nspnod_t* nsp, char* key, naic_nspnod_t** entry, int search)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/namespace/naic_nsp_rule_var_get.c */
extern
NAIG_ERR_T naic_nsp_rule_var_get
  (naic_nspnod_t* nsp, char* key, unsigned* slot)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_alts.c */
extern
NAIG_ERR_T naic_compile_alts
  (naic_t* naic, naio_resobj_t* alts)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_any.c */
extern
NAIG_ERR_T naic_compile_any
  (naic_t* naic)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_bitmask.c */
extern
NAIG_ERR_T naic_compile_bitmask
  (naic_t* naic, naio_resobj_t* bitmask)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_capture.c */
extern
NAIG_ERR_T naic_compile_capture
  (naic_t* naic, naio_resobj_t* group)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_endforce.c */
extern
NAIG_ERR_T naic_compile_endforce
  (naic_t* naic, naio_resobj_t* end)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_get_quantifiers.c */
extern
NAIG_ERR_T naic_compile_get_quantifiers
  (naic_t* naic, naio_resobj_t* quant, int range[ 2 ])
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_group.c */
extern
NAIG_ERR_T naic_compile_group
  (naic_t* naic, naio_resobj_t* group)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_hexliteral.c */
extern
NAIG_ERR_T naic_compile_hexliteral
  (naic_t* naic, naio_resobj_t* hex)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_limitedcall.c */
extern
NAIG_ERR_T naic_compile_limitedcall
  (naic_t* naic, naio_resobj_t* lc)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_macro.c */
extern
NAIG_ERR_T naic_compile_macro
  (naic_t* naic, naio_resobj_t* macro)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_matcher.c */
extern
NAIG_ERR_T naic_compile_matcher
  (naic_t* naic, naio_resobj_t* matcher)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_quantified_matcher.c */
extern
NAIG_ERR_T naic_compile_quantified_matcher
  (naic_t* naic, naio_resobj_t* matcher, int range[ 2 ])
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_quantified_matcher_trad.c */
extern
NAIG_ERR_T naic_compile_quantified_matcher_trad
  (naic_t* naic, naio_resobj_t* matcher, int range[ 2 ])
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_reference.c */
extern
NAIG_ERR_T naic_compile_reference
  (naic_t* naic, naio_resobj_t* ref)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_replace.c */
extern
NAIG_ERR_T naic_compile_replace
  (naic_t* naic, naio_resobj_t* tokens)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_rule.c */
extern
NAIG_ERR_T naic_compile_rule
  (naic_t* naic, naio_resobj_t* rule)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_set.c */
extern
NAIG_ERR_T naic_compile_set
  (naic_t* naic, naio_resobj_t* set)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_string.c */
extern
NAIG_ERR_T naic_compile_string
  (naic_t* naic, naio_resobj_t* string)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_term.c */
extern
NAIG_ERR_T naic_compile_term
  (naic_t* naic, naio_resobj_t* term)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_term_notand.c */
extern
NAIG_ERR_T naic_compile_term_notand
  (naic_t* naic, naio_resobj_t* term)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_term_quantified.c */
extern
NAIG_ERR_T naic_compile_term_quantified
  (naic_t* naic, naio_resobj_t* term)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_terms.c */
extern
NAIG_ERR_T naic_compile_terms
  (naic_t* naic, naio_resobj_t* terms)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_varcapture.c */
extern
NAIG_ERR_T naic_compile_varcapture
  (naic_t* naic, naio_resobj_t* capture)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_varref.c */
extern
NAIG_ERR_T naic_compile_varref
  (naic_t* naic, naio_resobj_t* ref)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_string_unescape.c */
extern
NAIG_ERR_T naic_string_unescape
  (
    naic_t* naic,
    unsigned start,
    unsigned stop,
    NAIG_ERR_T(*fnc)(naic_t*,unsigned,int)
  )
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/firstpass/naic_fp.c */
extern
NAIG_ERR_T naic_fp
  (naic_t* naic, naio_resobj_t* top, naic_nspnod_t** nsp)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/firstpass/naic_fp_import.c */
extern
NAIG_ERR_T naic_fp_import
  (naic_t* naic, naio_resobj_t* rule)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/firstpass/naic_fp_rule.c */
extern
NAIG_ERR_T naic_fp_rule
  (naic_t* naic, naio_resobj_t* rule, naic_nspnod_t* nsp)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/firstpass/naic_fp_rule_tree.c */
extern
NAIG_ERR_T naic_fp_rule_tree
  (naic_t* naic, naio_resobj_t* rule, naio_resobj_t* top)
  __attribute__ ((warn_unused_result));



#endif