/**
* \file
* \brief This file is an autogenerated function prototypes header file.
*
* Copyright 2018 K.J. Hermans
* WARNING: This file is automatically generated. Any changes will be lost.
*/

#ifndef ___LIB_COMPILER_FUNCTIONS_H_
#define ___LIB_COMPILER_FUNCTIONS_H_

/* declared in ./lib/compiler/naic_compile.c */
extern
NAIG_ERR_T naic_compile
  (
    char* grammar,
    naio_slotmap_t* slots,
    unsigned flags,
    NAIG_ERR_T(*fnc)(void*,char*,...),
    void* arg
  )
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/naic_compile_top.c */
extern
NAIG_ERR_T naic_compile_top
  (naic_t* naic, naio_resobj_t* top)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/naic_grammar_slotmap_string.c */
extern
char* naic_grammar_slotmap_string
  (unsigned slot)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/naic_reserve.c */
extern
NAIG_ERR_T naic_reserve
  (naic_t* naic, char* fmt, ...)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/naic_resobj_debug.c */
extern
void naic_resobj_debug
  (naio_resobj_t* obj);

/* declared in ./lib/compiler/script/naic_compile_assignment.c */
extern
NAIG_ERR_T naic_compile_assignment
  (naic_t* naic, naio_resobj_t* assignment)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_binop_p10.c */
extern
NAIG_ERR_T naic_compile_binop_p10
  (naic_t* naic, naio_resobj_t* expr)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_binop_p11.c */
extern
NAIG_ERR_T naic_compile_binop_p11
  (naic_t* naic, naio_resobj_t* expr)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_binop_p12.c */
extern
NAIG_ERR_T naic_compile_binop_p12
  (naic_t* naic, naio_resobj_t* expr)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_binop_p3.c */
extern
NAIG_ERR_T naic_compile_binop_p3
  (naic_t* naic, naio_resobj_t* expr)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_binop_p4.c */
extern
NAIG_ERR_T naic_compile_binop_p4
  (naic_t* naic, naio_resobj_t* expr)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_binop_p5.c */
extern
NAIG_ERR_T naic_compile_binop_p5
  (naic_t* naic, naio_resobj_t* expr)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_binop_p6.c */
extern
NAIG_ERR_T naic_compile_binop_p6
  (naic_t* naic, naio_resobj_t* expr)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_binop_p7.c */
extern
NAIG_ERR_T naic_compile_binop_p7
  (naic_t* naic, naio_resobj_t* expr)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_binop_p8.c */
extern
NAIG_ERR_T naic_compile_binop_p8
  (naic_t* naic, naio_resobj_t* expr)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_binop_p9.c */
extern
NAIG_ERR_T naic_compile_binop_p9
  (naic_t* naic, naio_resobj_t* expr)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_block_stmt.c */
extern
NAIG_ERR_T naic_compile_block_stmt
  (naic_t* naic, naio_resobj_t* stmt)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_expr.c */
extern
NAIG_ERR_T naic_compile_expr
  (naic_t* naic, naio_resobj_t* expr)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_expr_call.c */
extern
NAIG_ERR_T naic_compile_expr_call
  (naic_t* naic, naio_resobj_t* stmt)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_expr_reference.c */
extern
NAIG_ERR_T naic_compile_expr_reference
  (naic_t* naic, naio_resobj_t* ref)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_function.c */
extern
NAIG_ERR_T naic_compile_function
  (naic_t* naic, naio_resobj_t* func)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_function_body.c */
extern
NAIG_ERR_T naic_compile_function_body
  (naic_t* naic, naio_resobj_t* body)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_function_params.c */
extern
NAIG_ERR_T naic_compile_function_params
  (naic_t* naic, naio_resobj_t* params)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_function_stmt.c */
extern
NAIG_ERR_T naic_compile_function_stmt
  (naic_t* naic, naio_resobj_t* stmt)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_functioncall.c */
extern
NAIG_ERR_T naic_compile_functioncall
  (naic_t* naic, naio_resobj_t* call)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_global.c */
extern
NAIG_ERR_T naic_compile_global
  (naic_t* naic, naio_resobj_t* global)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_if.c */
extern
NAIG_ERR_T naic_compile_if
  (naic_t* naic, naio_resobj_t* f)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_return.c */
extern
NAIG_ERR_T naic_compile_return
  (naic_t* naic, naio_resobj_t* ret)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_scr_reference.c */
extern
NAIG_ERR_T naic_compile_scr_reference
  (naic_t* naic, naio_resobj_t* reference)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_scr_term.c */
extern
NAIG_ERR_T naic_compile_scr_term
  (naic_t* naic, naio_resobj_t* term)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_stmts.c */
extern
NAIG_ERR_T naic_compile_stmts
  (naic_t* naic, naio_resobj_t* stmts)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_vardecl.c */
extern
NAIG_ERR_T naic_compile_vardecl
  (naic_t* naic, naio_resobj_t* vardecl)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/script/naic_compile_while.c */
extern
NAIG_ERR_T naic_compile_while
  (naic_t* naic, naio_resobj_t* whl)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/namespace/naic_nsp_add.c */
extern
NAIG_ERR_T naic_nsp_add
  (naic_nspnod_t* nsp, naic_nspnod_t* entry)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/namespace/naic_nsp_add_block.c */
extern
NAIG_ERR_T naic_nsp_add_block
  (naic_nspnod_t* nsp, naio_resobj_t* object, naic_nspnod_t** block)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/namespace/naic_nsp_add_func.c */
extern
NAIG_ERR_T naic_nsp_add_func
  (naic_nspnod_t* nsp, char* name, naio_resobj_t* object, naic_nspnod_t** func)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/namespace/naic_nsp_add_global.c */
extern
NAIG_ERR_T naic_nsp_add_global
  (
    naic_nspnod_t* nsp,
    char* name,
    char* type,
    naio_resobj_t* object,
    naic_nspnod_t** var
  )
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/namespace/naic_nsp_add_rule.c */
extern
NAIG_ERR_T naic_nsp_add_rule
  (naic_nspnod_t* nsp, char* name, naio_resobj_t* object, naic_nspnod_t** rule)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/namespace/naic_nsp_add_rulevar.c */
extern
NAIG_ERR_T naic_nsp_add_rulevar
  (naic_nspnod_t* nsp, char* name, unsigned slot)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/namespace/naic_nsp_add_var.c */
extern
NAIG_ERR_T naic_nsp_add_var
  (
    naic_nspnod_t* nsp,
    char* name,
    char* type,
    naio_resobj_t* object,
    naic_nspnod_t** var
  )
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/namespace/naic_nsp_entry_new.c */
extern
NAIG_ERR_T naic_nsp_entry_new
  (
    naic_nspnod_t* parent,
    char* name,
    unsigned type,
    naio_resobj_t* object,
    naic_nspnod_t** result
  )
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/namespace/naic_nsp_function_update.c */
extern
NAIG_ERR_T naic_nsp_function_update
  (naic_nspnod_t* node)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/namespace/naic_nsp_get.c */
extern
NAIG_ERR_T naic_nsp_get
  (naic_nspnod_t* nsp, char* key, naic_nspnod_t** entry, int search)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/namespace/naic_nsp_rule_var_get.c */
extern
NAIG_ERR_T naic_nsp_rule_var_get
  (naic_nspnod_t* nsp, char* key, unsigned* slot)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_alts.c */
extern
NAIG_ERR_T naic_compile_alts
  (naic_t* naic, naio_resobj_t* alts)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_any.c */
extern
NAIG_ERR_T naic_compile_any
  (naic_t* naic)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_bitmask.c */
extern
NAIG_ERR_T naic_compile_bitmask
  (naic_t* naic, naio_resobj_t* bitmask)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_capture.c */
extern
NAIG_ERR_T naic_compile_capture
  (naic_t* naic, naio_resobj_t* group)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_endforce.c */
extern
NAIG_ERR_T naic_compile_endforce
  (naic_t* naic, naio_resobj_t* end)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_get_quantifiers.c */
extern
NAIG_ERR_T naic_compile_get_quantifiers
  (naic_t* naic, naio_resobj_t* quant, int range[ 2 ])
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_group.c */
extern
NAIG_ERR_T naic_compile_group
  (naic_t* naic, naio_resobj_t* group)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_hexliteral.c */
extern
NAIG_ERR_T naic_compile_hexliteral
  (naic_t* naic, naio_resobj_t* hex)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_limitedcall.c */
extern
NAIG_ERR_T naic_compile_limitedcall
  (naic_t* naic, naio_resobj_t* lc)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_macro.c */
extern
NAIG_ERR_T naic_compile_macro
  (naic_t* naic, naio_resobj_t* macro)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_matcher.c */
extern
NAIG_ERR_T naic_compile_matcher
  (naic_t* naic, naio_resobj_t* matcher)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_quantified_matcher.c */
extern
NAIG_ERR_T naic_compile_quantified_matcher
  (naic_t* naic, naio_resobj_t* matcher, int range[ 2 ])
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_quantified_matcher_trad.c */
extern
NAIG_ERR_T naic_compile_quantified_matcher_trad
  (naic_t* naic, naio_resobj_t* matcher, int range[ 2 ])
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_reference.c */
extern
NAIG_ERR_T naic_compile_reference
  (naic_t* naic, naio_resobj_t* ref)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_replace.c */
extern
NAIG_ERR_T naic_compile_replace
  (naic_t* naic, naio_resobj_t* tokens)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_rule.c */
extern
NAIG_ERR_T naic_compile_rule
  (naic_t* naic, naio_resobj_t* rule)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_set.c */
extern
NAIG_ERR_T naic_compile_set
  (naic_t* naic, naio_resobj_t* set)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_string.c */
extern
NAIG_ERR_T naic_compile_string
  (naic_t* naic, naio_resobj_t* string)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_term.c */
extern
NAIG_ERR_T naic_compile_term
  (naic_t* naic, naio_resobj_t* term)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_term_notand.c */
extern
NAIG_ERR_T naic_compile_term_notand
  (naic_t* naic, naio_resobj_t* term)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_term_quantified.c */
extern
NAIG_ERR_T naic_compile_term_quantified
  (naic_t* naic, naio_resobj_t* term)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_terms.c */
extern
NAIG_ERR_T naic_compile_terms
  (naic_t* naic, naio_resobj_t* terms)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_varcapture.c */
extern
NAIG_ERR_T naic_compile_varcapture
  (naic_t* naic, naio_resobj_t* capture)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_compile_varref.c */
extern
NAIG_ERR_T naic_compile_varref
  (naic_t* naic, naio_resobj_t* ref)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/rule/naic_string_unescape.c */
extern
NAIG_ERR_T naic_string_unescape
  (
    naic_t* naic,
    unsigned start,
    unsigned stop,
    NAIG_ERR_T(*fnc)(naic_t*,unsigned,int)
  )
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/firstpass/naic_fp.c */
extern
NAIG_ERR_T naic_fp
  (naic_t* naic, naio_resobj_t* top, naic_nspnod_t** nsp)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/firstpass/naic_fp_block.c */
extern
NAIG_ERR_T naic_fp_block
  (naic_t* naic, naio_resobj_t* block, naic_nspnod_t* nsp)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/firstpass/naic_fp_blockstmt.c */
extern
NAIG_ERR_T naic_fp_blockstmt
  (naic_t* naic, naio_resobj_t* stmt, naic_nspnod_t* nsp)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/firstpass/naic_fp_funcbody.c */
extern
NAIG_ERR_T naic_fp_funcbody
  (naic_t* naic, naio_resobj_t* body, naic_nspnod_t* func)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/firstpass/naic_fp_funcdecl.c */
extern
NAIG_ERR_T naic_fp_funcdecl
  (naic_t* naic, naio_resobj_t* func, naic_nspnod_t* nsp)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/firstpass/naic_fp_funcparams.c */
extern
NAIG_ERR_T naic_fp_funcparams
  (naic_t* naic, naio_resobj_t* params, naic_nspnod_t* func)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/firstpass/naic_fp_funcstmt.c */
extern
NAIG_ERR_T naic_fp_funcstmt
  (naic_t* naic, naio_resobj_t* stmt, naic_nspnod_t* nsp)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/firstpass/naic_fp_globaldecl.c */
extern
NAIG_ERR_T naic_fp_globaldecl
  (naic_t* naic, naio_resobj_t* var, naic_nspnod_t* nsp)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/firstpass/naic_fp_rule.c */
extern
NAIG_ERR_T naic_fp_rule
  (naic_t* naic, naio_resobj_t* rule, naic_nspnod_t* nsp)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/firstpass/naic_fp_rule_tree.c */
extern
NAIG_ERR_T naic_fp_rule_tree
  (naic_t* naic, naio_resobj_t* rule, naio_resobj_t* top)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/firstpass/naic_fp_stmtif.c */
extern
NAIG_ERR_T naic_fp_stmtif
  (naic_t* naic, naio_resobj_t* f, naic_nspnod_t* nsp)
  __attribute__ ((warn_unused_result));

/* declared in ./lib/compiler/firstpass/naic_fp_vardecl.c */
extern
NAIG_ERR_T naic_fp_vardecl
  (naic_t* naic, naio_resobj_t* var, naic_nspnod_t* nsp)
  __attribute__ ((warn_unused_result));



#endif