/** THIS FILE IS AUTOGENERATED **/

/**
 * This file is part of Naigama, a parser engine.

Copyright (c) 2020, Kees-Jan Hermans <kees.jan.hermans@gmail.com>
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the <organization> nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

 *
 * \file
 * \brief
 */

#include "naie_private.h"

/**
 * Returns a string value for each opcode.
 * This C file is automatically generated.
 */
char* naie_instr_string
  (uint32_t opcode)
{
  switch (opcode) {
    case OPCODE_ANY: return "ANY";
    case OPCODE_BACKCOMMIT: return "BACKCOMMIT";
    case OPCODE_CALL: return "CALL";
    case OPCODE_CATCH: return "CATCH";
    case OPCODE_CHAR: return "CHAR";
    case OPCODE_CLOSECAPTURE: return "CLOSECAPTURE";
    case OPCODE_COMMIT: return "COMMIT";
    case OPCODE_CONDJUMP: return "CONDJUMP";
    case OPCODE_COUNTER: return "COUNTER";
    case OPCODE_END: return "END";
    case OPCODE_ENDISOLATE: return "ENDISOLATE";
    case OPCODE_ENDREPLACE: return "ENDREPLACE";
    case OPCODE_FAIL: return "FAIL";
    case OPCODE_FAILTWICE: return "FAILTWICE";
    case OPCODE_ISOLATE: return "ISOLATE";
    case OPCODE_JUMP: return "JUMP";
    case OPCODE_MASKEDCHAR: return "MASKEDCHAR";
    case OPCODE_NOOP: return "NOOP";
    case OPCODE_OPENCAPTURE: return "OPENCAPTURE";
    case OPCODE_PARTIALCOMMIT: return "PARTIALCOMMIT";
    case OPCODE_QUAD: return "QUAD";
    case OPCODE_RANGE: return "RANGE";
    case OPCODE_REPLACE: return "REPLACE";
    case OPCODE_RET: return "RET";
    case OPCODE_SCR_ADD: return "SCR_ADD";
    case OPCODE_SCR_ASSIGN: return "SCR_ASSIGN";
    case OPCODE_SCR_BITAND: return "SCR_BITAND";
    case OPCODE_SCR_BITANDIS: return "SCR_BITANDIS";
    case OPCODE_SCR_BITNOT: return "SCR_BITNOT";
    case OPCODE_SCR_BITNOTIS: return "SCR_BITNOTIS";
    case OPCODE_SCR_BITOR: return "SCR_BITOR";
    case OPCODE_SCR_BITORIS: return "SCR_BITORIS";
    case OPCODE_SCR_BITXOR: return "SCR_BITXOR";
    case OPCODE_SCR_BITXORIS: return "SCR_BITXORIS";
    case OPCODE_SCR_CALL: return "SCR_CALL";
    case OPCODE_SCR_CONDJUMP: return "SCR_CONDJUMP";
    case OPCODE_SCR_DEC: return "SCR_DEC";
    case OPCODE_SCR_DIV: return "SCR_DIV";
    case OPCODE_SCR_EQUALS: return "SCR_EQUALS";
    case OPCODE_SCR_GT: return "SCR_GT";
    case OPCODE_SCR_GTEQ: return "SCR_GTEQ";
    case OPCODE_SCR_INC: return "SCR_INC";
    case OPCODE_SCR_JUMP: return "SCR_JUMP";
    case OPCODE_SCR_LOGAND: return "SCR_LOGAND";
    case OPCODE_SCR_LOGNOT: return "SCR_LOGNOT";
    case OPCODE_SCR_LOGOR: return "SCR_LOGOR";
    case OPCODE_SCR_LT: return "SCR_LT";
    case OPCODE_SCR_LTEQ: return "SCR_LTEQ";
    case OPCODE_SCR_MUL: return "SCR_MUL";
    case OPCODE_SCR_NEQUALS: return "SCR_NEQUALS";
    case OPCODE_SCR_POP: return "SCR_POP";
    case OPCODE_SCR_POW: return "SCR_POW";
    case OPCODE_SCR_PUSH: return "SCR_PUSH";
    case OPCODE_SCR_RET: return "SCR_RET";
    case OPCODE_SCR_SHIFTIN: return "SCR_SHIFTIN";
    case OPCODE_SCR_SHIFTINIS: return "SCR_SHIFTINIS";
    case OPCODE_SCR_SHIFTOUT: return "SCR_SHIFTOUT";
    case OPCODE_SCR_SHIFTOUTIS: return "SCR_SHIFTOUTIS";
    case OPCODE_SCR_SUB: return "SCR_SUB";
    case OPCODE_SET: return "SET";
    case OPCODE_SKIP: return "SKIP";
    case OPCODE_SPAN: return "SPAN";
    case OPCODE_TESTANY: return "TESTANY";
    case OPCODE_TESTCHAR: return "TESTCHAR";
    case OPCODE_TESTQUAD: return "TESTQUAD";
    case OPCODE_TESTSET: return "TESTSET";
    case OPCODE_TRAP: return "TRAP";
    case OPCODE_VAR: return "VAR";

  }
  return "";
}
