/**
* \file
* \brief This file is an autogenerated function prototypes header file.
*
* Copyright 2018 K.J. Hermans
* WARNING: This file is automatically generated. Any changes will be lost.
*/

#ifndef ____GEN1_LIB_ASSEMBLER__FUNCTIONS_H_
#define ____GEN1_LIB_ASSEMBLER__FUNCTIONS_H_

/* declared in ../gen1/lib/assembler//naia_assemble.c */
extern
NAIG_ERR_T naia_assemble
  (
    char* assembly,
    FILE* labelmap,
    int debug,
    NAIG_ERR_T(*write)(void* ptr, unsigned size, void* arg),
    void* arg
  )
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_label_get.c */
extern
NAIG_ERR_T naia_label_get
  (naia_t* naia, char* str, unsigned len, unsigned* offset)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_label_map_write.c */
extern
NAIG_ERR_T naia_label_map_write
  (naia_t* naia, FILE* map)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_label_put.c */
extern
NAIG_ERR_T naia_label_put
  (naia_t* naia, char* str, unsigned len, unsigned offset)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_any.c */
extern
NAIG_ERR_T naia_process_any
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_backcommit.c */
extern
NAIG_ERR_T naia_process_backcommit
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_call.c */
extern
NAIG_ERR_T naia_process_call
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_catch.c */
extern
NAIG_ERR_T naia_process_catch
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_char.c */
extern
NAIG_ERR_T naia_process_char
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_closecapture.c */
extern
NAIG_ERR_T naia_process_closecapture
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_commit.c */
extern
NAIG_ERR_T naia_process_commit
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_condjump.c */
extern
NAIG_ERR_T naia_process_condjump
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_counter.c */
extern
NAIG_ERR_T naia_process_counter
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_end.c */
extern
NAIG_ERR_T naia_process_end
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_endreplace.c */
extern
NAIG_ERR_T naia_process_endreplace
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_fail.c */
extern
NAIG_ERR_T naia_process_fail
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_failtwice.c */
extern
NAIG_ERR_T naia_process_failtwice
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_instructions.c */
extern
NAIG_ERR_T naia_process_instructions
  (naia_t* naia)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_jump.c */
extern
NAIG_ERR_T naia_process_jump
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_labels.c */
extern
NAIG_ERR_T naia_process_labels
  (naia_t* naia)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_maskedchar.c */
extern
NAIG_ERR_T naia_process_maskedchar
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_noop.c */
extern
NAIG_ERR_T naia_process_noop
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_opencapture.c */
extern
NAIG_ERR_T naia_process_opencapture
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_partialcommit.c */
extern
NAIG_ERR_T naia_process_partialcommit
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_quad.c */
extern
NAIG_ERR_T naia_process_quad
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_replace.c */
extern
NAIG_ERR_T naia_process_replace
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_ret.c */
extern
NAIG_ERR_T naia_process_ret
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_set.c */
extern
NAIG_ERR_T naia_process_set
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_skip.c */
extern
NAIG_ERR_T naia_process_skip
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_span.c */
extern
NAIG_ERR_T naia_process_span
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_testany.c */
extern
NAIG_ERR_T naia_process_testany
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_testchar.c */
extern
NAIG_ERR_T naia_process_testchar
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_testquad.c */
extern
NAIG_ERR_T naia_process_testquad
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_testset.c */
extern
NAIG_ERR_T naia_process_testset
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_tokens.c */
extern
NAIG_ERR_T naia_process_tokens
  (naia_t* naia)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_trap.c */
extern
NAIG_ERR_T naia_process_trap
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_process_var.c */
extern
NAIG_ERR_T naia_process_var
  (naia_t* naia, unsigned i)
  __attribute__ ((warn_unused_result));

/* declared in ../gen1/lib/assembler//naia_slotmap_string.c */
extern
char* naia_slotmap_string
  (unsigned slot)
  __attribute__ ((warn_unused_result));



#endif